const sharp = require('sharp');
const fs = require('fs');
const path = require('path');

async function main() {
  const publicDir = path.join(__dirname, '..', 'public');
  const catsDir = path.join(publicDir, 'images', 'cats');
  const matkiDir = path.join(publicDir, 'images', 'matki');
  const logoPath = 'C:\\Users\\Michu\\Desktop\\logo.jpeg';
  const agaDir = 'C:\\Users\\Michu\\Desktop\\aga';
  const matkiSourceDir = 'C:\\Users\\Michu\\Desktop\\aga\\matki';

  fs.mkdirSync(catsDir, { recursive: true });
  fs.mkdirSync(matkiDir, { recursive: true });

  console.log('--- Converting Logo ---');
  await sharp(logoPath).png().toFile(path.join(publicDir, 'logo.png'));
  await sharp(logoPath).webp({ quality: 95 }).toFile(path.join(publicDir, 'logo.webp'));
  console.log('Logo saved as logo.webp and logo.png');

  console.log('--- Converting Matki ---');
  const matkiFiles = fs.readdirSync(matkiSourceDir).filter(f => /\.(jpe?g|jfif|png)$/i.test(f));
  const matkiList = [];
  let mIdx = 1;
  for (const file of matkiFiles) {
    const src = path.join(matkiSourceDir, file);
    const outName = `matka_${String(mIdx).padStart(2, '0')}.webp`;
    const dest = path.join(matkiDir, outName);
    try {
      const meta = await sharp(src)
        .resize({ width: 1400, withoutEnlargement: true })
        .webp({ quality: 85 })
        .toFile(dest);
      matkiList.push({
        id: `matka-${mIdx}`,
        src: `/images/matki/${outName}`,
        width: meta.width,
        height: meta.height,
        aspect: meta.width / meta.height > 1 ? 'landscape' : 'portrait',
        originalFile: file
      });
      console.log(`Converted matka ${mIdx}: ${file} -> ${outName}`);
      mIdx++;
    } catch (err) {
      console.error(`Failed converting matka ${file}:`, err.message);
    }
  }

  console.log('--- Converting Cats from aga ---');
  const agaFiles = fs.readdirSync(agaDir).filter(f => /\.(jpe?g|jfif|png)$/i.test(f));
  console.log(`Found ${agaFiles.length} photos in aga`);

  const galleryList = [];
  let cIdx = 1;
  for (const file of agaFiles) {
    const src = path.join(agaDir, file);
    const outName = `cat_${String(cIdx).padStart(2, '0')}.webp`;
    const dest = path.join(catsDir, outName);
    try {
      const meta = await sharp(src)
        .resize({ width: 1400, withoutEnlargement: true })
        .webp({ quality: 85 })
        .toFile(dest);
      
      // Heuristic tagging based on aspect ratio or index
      let category = 'domowe';
      if (cIdx % 4 === 0) category = 'kociaki';
      else if (cIdx % 3 === 0) category = 'kocury';
      else if (cIdx % 2 === 0) category = 'kotki';
      else category = 'zycie_w_domu';

      galleryList.push({
        id: `cat-${cIdx}`,
        src: `/images/cats/${outName}`,
        width: meta.width,
        height: meta.height,
        aspect: meta.width / meta.height > 1 ? 'landscape' : (meta.width === meta.height ? 'square' : 'portrait'),
        category,
        title: `Maine Coon Koci Przyjaciel #${cIdx}`,
        originalFile: file
      });
      cIdx++;
    } catch (err) {
      console.error(`Failed converting cat photo ${file}:`, err.message);
    }
  }
  console.log(`Successfully converted ${galleryList.length} photos from aga!`);

  // Write catalog data to src/data/realCatsData.ts
  const tsContent = `// Autogenerated real cats and gallery data from C:\\Users\\Michu\\Desktop\\aga
export interface CatPhoto {
  id: string;
  src: string;
  width: number;
  height: number;
  aspect: 'landscape' | 'portrait' | 'square';
  category: string;
  title: string;
}

export const REAL_LOGO = '/logo.webp';
export const REAL_FACEBOOK_URL = 'https://www.facebook.com/profile.php?id=100063684877717';
export const REAL_PHONE = '698 837 525';
export const REAL_PHONE_RAW = '+48698837525';
export const REAL_LOCATION = 'Wrocław i okolice, Dolny Śląsk';

export const MATKI_PHOTOS: CatPhoto[] = ${JSON.stringify(matkiList, null, 2)};

export const GALLERY_PHOTOS: CatPhoto[] = ${JSON.stringify(galleryList, null, 2)};

// Best featured photos for specific sections
export const HERO_CATS = ${JSON.stringify(galleryList.slice(0, 6), null, 2)};
export const KITTEN_FEATURED = ${JSON.stringify(galleryList.slice(6, 14), null, 2)};
export const HOME_LIFE_FEATURED = ${JSON.stringify(galleryList.slice(14, 24), null, 2)};
`;

  const dataDir = path.join(__dirname, '..', 'src', 'data');
  fs.mkdirSync(dataDir, { recursive: true });
  fs.writeFileSync(path.join(dataDir, 'realCatsData.ts'), tsContent, 'utf-8');
  console.log('Saved src/data/realCatsData.ts successfully!');
}

main().catch(err => {
  console.error('Fatal error in script:', err);
  process.exit(1);
});
