// Auto-generated by scripts/import_aga_photos.mjs
export interface GalleryPhotoItem {
  id: string;
  src: string;
  category: "wybieg" | "kocury" | "matki" | "mlode" | "w-domu" | "wyprawka";
  categoryLabel: string;
  title: string;
  caption: string;
  bentoSpan?: string;
  editorialDesc?: string;
  badge?: string;
}

export const AGA_CATEGORIES = [
  { id: "all", label: "🌟 Wszystkie" },
  { id: "wybieg", label: "🌿 Wybieg" },
  { id: "kocury", label: "🦁 Kocury" },
  { id: "matki", label: "🌸 Matki" },
  { id: "mlode", label: "🍼 Młode" },
  { id: "w-domu", label: "🏡 W domu" },
  { id: "wyprawka", label: "🎁 Wyprawka" },
] as const;

export const HOMEPAGE_SHOWCASE_PHOTOS: GalleryPhotoItem[] = [
  {
    "id": "showcase-1",
    "src": "/images/gallery/wybieg/wybieg_001.jpeg",
    "category": "wybieg",
    "categoryLabel": "🌿 Wybieg i Ogród",
    "title": "Całoroczny Wybieg i Ogród",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Wybieg i Ogród)",
    "bentoSpan": "col-span-2 row-span-2 sm:col-span-2 sm:row-span-2 lg:col-span-2 lg:row-span-2",
    "editorialDesc": "Bezpieczna woliera z pniami dębowymi do 3.2m wysokości i bezpośrednim przejściem z salonu.",
    "badge": "🌿 WOLIERA 365 DNI"
  },
  {
    "id": "showcase-2",
    "src": "/images/gallery/kocury/kocury_001.jpeg",
    "category": "kocury",
    "categoryLabel": "🦁 Kocury Hodowlane",
    "title": "Majestatyczne Kocury",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocur Hodowlany)",
    "bentoSpan": "col-span-1 row-span-2 sm:col-span-1 sm:row-span-2 lg:col-span-1 lg:row-span-2",
    "editorialDesc": "Potężne reproduktory o wadze dochodzącej do 12 kg i łagodnym, ufnym sercu.",
    "badge": "🦁 POTĘŻNY SAMIEC"
  },
  {
    "id": "showcase-3",
    "src": "/images/gallery/mlode/mlode_001.jpeg",
    "category": "mlode",
    "categoryLabel": "🍼 Młode i Maluchy",
    "title": "Maluchy z Miotów 2026",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocię Maine Coon)",
    "bentoSpan": "col-span-1 row-span-1 sm:col-span-1 sm:row-span-1 lg:col-span-1 lg:row-span-1",
    "editorialDesc": "Wychowane na kolanach i przyzwyczajone do obecności dzieci od pierwszych dni.",
    "badge": "🍼 MIOTY 2026"
  },
  {
    "id": "showcase-4",
    "src": "/images/gallery/matki/matki_001.jpeg",
    "category": "matki",
    "categoryLabel": "🌸 Matki Hodowlane",
    "title": "Czułe Matki Hodowlane",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kotka Hodowlana)",
    "bentoSpan": "col-span-1 row-span-1 sm:col-span-1 sm:row-span-1 lg:col-span-1 lg:row-span-1",
    "editorialDesc": "Zdrowe kotki z pełnym profilem DNA Laboklin i badaniem Echo Doppler HCM.",
    "badge": "🌸 NASZE KRÓLOWE"
  },
  {
    "id": "showcase-5",
    "src": "/images/gallery/w-domu/w-domu_001.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Sercu Domu",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)",
    "bentoSpan": "col-span-2 row-span-1 sm:col-span-2 sm:row-span-1 lg:col-span-2 lg:row-span-1",
    "editorialDesc": "Koty śpią w naszych łóżkach i spędzają całe dnie na salonowych kanapach.",
    "badge": "🏡 BEZ KLATEK"
  },
  {
    "id": "showcase-6",
    "src": "/images/gallery/mlode/mlode_004.jpeg",
    "category": "mlode",
    "categoryLabel": "🍼 Młode i Maluchy",
    "title": "Ciekawość Świata",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocię Maine Coon)",
    "bentoSpan": "col-span-1 row-span-1 sm:col-span-1 sm:row-span-1 lg:col-span-1 lg:row-span-1",
    "editorialDesc": "Rysie pędzle na uszach i wspaniała, ufna osobowość małego olbrzyma.",
    "badge": "🐾 SREBRZYSTY KLASYK"
  },
  {
    "id": "showcase-7",
    "src": "/images/gallery/w-domu/w-domu_005.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Więź z Dziećmi i Psem",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)",
    "bentoSpan": "col-span-1 row-span-1 sm:col-span-1 sm:row-span-1 lg:col-span-1 lg:row-span-1",
    "editorialDesc": "Zero lęku, 100% zaufania. Pełna socjalizacja z domowymi zwierzętami i hałasem.",
    "badge": "❤️ SOCJALIZACJA"
  },
  {
    "id": "showcase-8",
    "src": "/images/gallery/kocury/kocury_003.jpeg",
    "category": "kocury",
    "categoryLabel": "🦁 Kocury Hodowlane",
    "title": "Dostojne Spojrzenie",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocur Hodowlany)",
    "bentoSpan": "col-span-1 row-span-1 sm:col-span-1 sm:row-span-1 lg:col-span-1 lg:row-span-1",
    "editorialDesc": "Głęboki profil, mocna broda i bursztynowe, hipnotyzujące spojrzenie.",
    "badge": "👑 PROFIL WZORCA"
  },
  {
    "id": "showcase-9",
    "src": "/images/gallery/wyprawka/wyprawka_001.jpeg",
    "category": "wyprawka",
    "categoryLabel": "🎁 Wyprawka",
    "title": "Luksusowa Wyprawka",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Luksusowa Wyprawka)",
    "bentoSpan": "col-span-1 row-span-1 sm:col-span-1 sm:row-span-1 lg:col-span-1 lg:row-span-1",
    "editorialDesc": "Kompletna karma, legowisko z zapachem mamy, zabawki i dokumenty rodowodowe.",
    "badge": "🎁 NA START"
  },
  {
    "id": "showcase-10",
    "src": "/images/gallery/wybieg/wybieg_003.jpeg",
    "category": "wybieg",
    "categoryLabel": "🌿 Wybieg i Ogród",
    "title": "Zadaszona Strefa Relaksu",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Wybieg i Ogród)",
    "bentoSpan": "col-span-2 row-span-1 sm:col-span-2 sm:row-span-1 lg:col-span-2 lg:row-span-1",
    "editorialDesc": "Natura, śpiew ptaków i świeże wrocławskie powietrze każdego dnia.",
    "badge": "🌲 PRZESTRZEŃ"
  }
];

export const ALL_AGA_PHOTOS: GalleryPhotoItem[] = [
  {
    "id": "wybieg-1",
    "src": "/images/gallery/wybieg/wybieg_001.jpeg",
    "category": "wybieg",
    "categoryLabel": "🌿 Wybieg i Ogród",
    "title": "Wybieg i Ogród #1",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Wybieg i Ogród)"
  },
  {
    "id": "wybieg-2",
    "src": "/images/gallery/wybieg/wybieg_002.jpeg",
    "category": "wybieg",
    "categoryLabel": "🌿 Wybieg i Ogród",
    "title": "Wybieg i Ogród #2",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Wybieg i Ogród)"
  },
  {
    "id": "wybieg-3",
    "src": "/images/gallery/wybieg/wybieg_003.jpeg",
    "category": "wybieg",
    "categoryLabel": "🌿 Wybieg i Ogród",
    "title": "Wybieg i Ogród #3",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Wybieg i Ogród)"
  },
  {
    "id": "wybieg-4",
    "src": "/images/gallery/wybieg/wybieg_004.jpeg",
    "category": "wybieg",
    "categoryLabel": "🌿 Wybieg i Ogród",
    "title": "Wybieg i Ogród #4",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Wybieg i Ogród)"
  },
  {
    "id": "wybieg-5",
    "src": "/images/gallery/wybieg/wybieg_005.jpeg",
    "category": "wybieg",
    "categoryLabel": "🌿 Wybieg i Ogród",
    "title": "Wybieg i Ogród #5",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Wybieg i Ogród)"
  },
  {
    "id": "wybieg-6",
    "src": "/images/gallery/wybieg/wybieg_006.jpeg",
    "category": "wybieg",
    "categoryLabel": "🌿 Wybieg i Ogród",
    "title": "Wybieg i Ogród #6",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Wybieg i Ogród)"
  },
  {
    "id": "wybieg-7",
    "src": "/images/gallery/wybieg/wybieg_007.jpeg",
    "category": "wybieg",
    "categoryLabel": "🌿 Wybieg i Ogród",
    "title": "Wybieg i Ogród #7",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Wybieg i Ogród)"
  },
  {
    "id": "wybieg-8",
    "src": "/images/gallery/wybieg/wybieg_008.jpeg",
    "category": "wybieg",
    "categoryLabel": "🌿 Wybieg i Ogród",
    "title": "Wybieg i Ogród #8",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Wybieg i Ogród)"
  },
  {
    "id": "wybieg-9",
    "src": "/images/gallery/wybieg/wybieg_009.jpeg",
    "category": "wybieg",
    "categoryLabel": "🌿 Wybieg i Ogród",
    "title": "Wybieg i Ogród #9",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Wybieg i Ogród)"
  },
  {
    "id": "kocury-1",
    "src": "/images/gallery/kocury/kocury_001.jpeg",
    "category": "kocury",
    "categoryLabel": "🦁 Kocury Hodowlane",
    "title": "Kocur Hodowlany #1",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocur Hodowlany)"
  },
  {
    "id": "kocury-2",
    "src": "/images/gallery/kocury/kocury_002.jpeg",
    "category": "kocury",
    "categoryLabel": "🦁 Kocury Hodowlane",
    "title": "Kocur Hodowlany #2",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocur Hodowlany)"
  },
  {
    "id": "kocury-3",
    "src": "/images/gallery/kocury/kocury_003.jpeg",
    "category": "kocury",
    "categoryLabel": "🦁 Kocury Hodowlane",
    "title": "Kocur Hodowlany #3",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocur Hodowlany)"
  },
  {
    "id": "kocury-4",
    "src": "/images/gallery/kocury/kocury_004.jpeg",
    "category": "kocury",
    "categoryLabel": "🦁 Kocury Hodowlane",
    "title": "Kocur Hodowlany #4",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocur Hodowlany)"
  },
  {
    "id": "kocury-5",
    "src": "/images/gallery/kocury/kocury_005.jpeg",
    "category": "kocury",
    "categoryLabel": "🦁 Kocury Hodowlane",
    "title": "Kocur Hodowlany #5",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocur Hodowlany)"
  },
  {
    "id": "kocury-6",
    "src": "/images/gallery/kocury/kocury_006.jpeg",
    "category": "kocury",
    "categoryLabel": "🦁 Kocury Hodowlane",
    "title": "Kocur Hodowlany #6",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocur Hodowlany)"
  },
  {
    "id": "kocury-7",
    "src": "/images/gallery/kocury/kocury_007.jpeg",
    "category": "kocury",
    "categoryLabel": "🦁 Kocury Hodowlane",
    "title": "Kocur Hodowlany #7",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocur Hodowlany)"
  },
  {
    "id": "kocury-8",
    "src": "/images/gallery/kocury/kocury_008.jpeg",
    "category": "kocury",
    "categoryLabel": "🦁 Kocury Hodowlane",
    "title": "Kocur Hodowlany #8",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocur Hodowlany)"
  },
  {
    "id": "kocury-9",
    "src": "/images/gallery/kocury/kocury_009.jpeg",
    "category": "kocury",
    "categoryLabel": "🦁 Kocury Hodowlane",
    "title": "Kocur Hodowlany #9",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocur Hodowlany)"
  },
  {
    "id": "kocury-10",
    "src": "/images/gallery/kocury/kocury_010.jpeg",
    "category": "kocury",
    "categoryLabel": "🦁 Kocury Hodowlane",
    "title": "Kocur Hodowlany #10",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocur Hodowlany)"
  },
  {
    "id": "kocury-11",
    "src": "/images/gallery/kocury/kocury_011.jpeg",
    "category": "kocury",
    "categoryLabel": "🦁 Kocury Hodowlane",
    "title": "Kocur Hodowlany #11",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocur Hodowlany)"
  },
  {
    "id": "kocury-12",
    "src": "/images/gallery/kocury/kocury_012.jpeg",
    "category": "kocury",
    "categoryLabel": "🦁 Kocury Hodowlane",
    "title": "Kocur Hodowlany #12",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocur Hodowlany)"
  },
  {
    "id": "kocury-13",
    "src": "/images/gallery/kocury/kocury_013.jpeg",
    "category": "kocury",
    "categoryLabel": "🦁 Kocury Hodowlane",
    "title": "Kocur Hodowlany #13",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocur Hodowlany)"
  },
  {
    "id": "kocury-14",
    "src": "/images/gallery/kocury/kocury_014.jpeg",
    "category": "kocury",
    "categoryLabel": "🦁 Kocury Hodowlane",
    "title": "Kocur Hodowlany #14",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocur Hodowlany)"
  },
  {
    "id": "kocury-15",
    "src": "/images/gallery/kocury/kocury_015.jpeg",
    "category": "kocury",
    "categoryLabel": "🦁 Kocury Hodowlane",
    "title": "Kocur Hodowlany #15",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocur Hodowlany)"
  },
  {
    "id": "kocury-16",
    "src": "/images/gallery/kocury/kocury_016.jpeg",
    "category": "kocury",
    "categoryLabel": "🦁 Kocury Hodowlane",
    "title": "Kocur Hodowlany #16",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocur Hodowlany)"
  },
  {
    "id": "kocury-17",
    "src": "/images/gallery/kocury/kocury_017.jpeg",
    "category": "kocury",
    "categoryLabel": "🦁 Kocury Hodowlane",
    "title": "Kocur Hodowlany #17",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocur Hodowlany)"
  },
  {
    "id": "kocury-18",
    "src": "/images/gallery/kocury/kocury_018.jpeg",
    "category": "kocury",
    "categoryLabel": "🦁 Kocury Hodowlane",
    "title": "Kocur Hodowlany #18",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocur Hodowlany)"
  },
  {
    "id": "kocury-19",
    "src": "/images/gallery/kocury/kocury_019.jpeg",
    "category": "kocury",
    "categoryLabel": "🦁 Kocury Hodowlane",
    "title": "Kocur Hodowlany #19",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocur Hodowlany)"
  },
  {
    "id": "kocury-20",
    "src": "/images/gallery/kocury/kocury_020.jpeg",
    "category": "kocury",
    "categoryLabel": "🦁 Kocury Hodowlane",
    "title": "Kocur Hodowlany #20",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocur Hodowlany)"
  },
  {
    "id": "kocury-21",
    "src": "/images/gallery/kocury/kocury_021.jpeg",
    "category": "kocury",
    "categoryLabel": "🦁 Kocury Hodowlane",
    "title": "Kocur Hodowlany #21",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocur Hodowlany)"
  },
  {
    "id": "kocury-22",
    "src": "/images/gallery/kocury/kocury_022.jpeg",
    "category": "kocury",
    "categoryLabel": "🦁 Kocury Hodowlane",
    "title": "Kocur Hodowlany #22",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocur Hodowlany)"
  },
  {
    "id": "kocury-23",
    "src": "/images/gallery/kocury/kocury_023.jpeg",
    "category": "kocury",
    "categoryLabel": "🦁 Kocury Hodowlane",
    "title": "Kocur Hodowlany #23",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocur Hodowlany)"
  },
  {
    "id": "kocury-24",
    "src": "/images/gallery/kocury/kocury_024.jpeg",
    "category": "kocury",
    "categoryLabel": "🦁 Kocury Hodowlane",
    "title": "Kocur Hodowlany #24",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocur Hodowlany)"
  },
  {
    "id": "kocury-25",
    "src": "/images/gallery/kocury/kocury_025.jpeg",
    "category": "kocury",
    "categoryLabel": "🦁 Kocury Hodowlane",
    "title": "Kocur Hodowlany #25",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocur Hodowlany)"
  },
  {
    "id": "kocury-26",
    "src": "/images/gallery/kocury/kocury_026.jpeg",
    "category": "kocury",
    "categoryLabel": "🦁 Kocury Hodowlane",
    "title": "Kocur Hodowlany #26",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocur Hodowlany)"
  },
  {
    "id": "kocury-27",
    "src": "/images/gallery/kocury/kocury_027.jpeg",
    "category": "kocury",
    "categoryLabel": "🦁 Kocury Hodowlane",
    "title": "Kocur Hodowlany #27",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocur Hodowlany)"
  },
  {
    "id": "kocury-28",
    "src": "/images/gallery/kocury/kocury_028.jpeg",
    "category": "kocury",
    "categoryLabel": "🦁 Kocury Hodowlane",
    "title": "Kocur Hodowlany #28",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocur Hodowlany)"
  },
  {
    "id": "kocury-29",
    "src": "/images/gallery/kocury/kocury_029.jpeg",
    "category": "kocury",
    "categoryLabel": "🦁 Kocury Hodowlane",
    "title": "Kocur Hodowlany #29",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocur Hodowlany)"
  },
  {
    "id": "kocury-30",
    "src": "/images/gallery/kocury/kocury_030.jpeg",
    "category": "kocury",
    "categoryLabel": "🦁 Kocury Hodowlane",
    "title": "Kocur Hodowlany #30",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocur Hodowlany)"
  },
  {
    "id": "kocury-31",
    "src": "/images/gallery/kocury/kocury_031.jpeg",
    "category": "kocury",
    "categoryLabel": "🦁 Kocury Hodowlane",
    "title": "Kocur Hodowlany #31",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocur Hodowlany)"
  },
  {
    "id": "kocury-32",
    "src": "/images/gallery/kocury/kocury_032.jpeg",
    "category": "kocury",
    "categoryLabel": "🦁 Kocury Hodowlane",
    "title": "Kocur Hodowlany #32",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocur Hodowlany)"
  },
  {
    "id": "kocury-33",
    "src": "/images/gallery/kocury/kocury_033.jpeg",
    "category": "kocury",
    "categoryLabel": "🦁 Kocury Hodowlane",
    "title": "Kocur Hodowlany #33",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocur Hodowlany)"
  },
  {
    "id": "kocury-34",
    "src": "/images/gallery/kocury/kocury_034.jpeg",
    "category": "kocury",
    "categoryLabel": "🦁 Kocury Hodowlane",
    "title": "Kocur Hodowlany #34",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocur Hodowlany)"
  },
  {
    "id": "kocury-35",
    "src": "/images/gallery/kocury/kocury_035.jpeg",
    "category": "kocury",
    "categoryLabel": "🦁 Kocury Hodowlane",
    "title": "Kocur Hodowlany #35",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocur Hodowlany)"
  },
  {
    "id": "kocury-36",
    "src": "/images/gallery/kocury/kocury_036.jpeg",
    "category": "kocury",
    "categoryLabel": "🦁 Kocury Hodowlane",
    "title": "Kocur Hodowlany #36",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocur Hodowlany)"
  },
  {
    "id": "kocury-37",
    "src": "/images/gallery/kocury/kocury_037.jpeg",
    "category": "kocury",
    "categoryLabel": "🦁 Kocury Hodowlane",
    "title": "Kocur Hodowlany #37",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocur Hodowlany)"
  },
  {
    "id": "kocury-38",
    "src": "/images/gallery/kocury/kocury_038.jpeg",
    "category": "kocury",
    "categoryLabel": "🦁 Kocury Hodowlane",
    "title": "Kocur Hodowlany #38",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocur Hodowlany)"
  },
  {
    "id": "kocury-39",
    "src": "/images/gallery/kocury/kocury_039.jpeg",
    "category": "kocury",
    "categoryLabel": "🦁 Kocury Hodowlane",
    "title": "Kocur Hodowlany #39",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocur Hodowlany)"
  },
  {
    "id": "kocury-40",
    "src": "/images/gallery/kocury/kocury_040.jpeg",
    "category": "kocury",
    "categoryLabel": "🦁 Kocury Hodowlane",
    "title": "Kocur Hodowlany #40",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocur Hodowlany)"
  },
  {
    "id": "kocury-41",
    "src": "/images/gallery/kocury/kocury_041.jpeg",
    "category": "kocury",
    "categoryLabel": "🦁 Kocury Hodowlane",
    "title": "Kocur Hodowlany #41",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocur Hodowlany)"
  },
  {
    "id": "kocury-42",
    "src": "/images/gallery/kocury/kocury_042.jpeg",
    "category": "kocury",
    "categoryLabel": "🦁 Kocury Hodowlane",
    "title": "Kocur Hodowlany #42",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocur Hodowlany)"
  },
  {
    "id": "kocury-43",
    "src": "/images/gallery/kocury/kocury_043.jpeg",
    "category": "kocury",
    "categoryLabel": "🦁 Kocury Hodowlane",
    "title": "Kocur Hodowlany #43",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocur Hodowlany)"
  },
  {
    "id": "kocury-44",
    "src": "/images/gallery/kocury/kocury_044.jpeg",
    "category": "kocury",
    "categoryLabel": "🦁 Kocury Hodowlane",
    "title": "Kocur Hodowlany #44",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocur Hodowlany)"
  },
  {
    "id": "kocury-45",
    "src": "/images/gallery/kocury/kocury_045.jpeg",
    "category": "kocury",
    "categoryLabel": "🦁 Kocury Hodowlane",
    "title": "Kocur Hodowlany #45",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocur Hodowlany)"
  },
  {
    "id": "kocury-46",
    "src": "/images/gallery/kocury/kocury_046.jpeg",
    "category": "kocury",
    "categoryLabel": "🦁 Kocury Hodowlane",
    "title": "Kocur Hodowlany #46",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocur Hodowlany)"
  },
  {
    "id": "kocury-47",
    "src": "/images/gallery/kocury/kocury_047.jpeg",
    "category": "kocury",
    "categoryLabel": "🦁 Kocury Hodowlane",
    "title": "Kocur Hodowlany #47",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocur Hodowlany)"
  },
  {
    "id": "kocury-48",
    "src": "/images/gallery/kocury/kocury_048.jpeg",
    "category": "kocury",
    "categoryLabel": "🦁 Kocury Hodowlane",
    "title": "Kocur Hodowlany #48",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocur Hodowlany)"
  },
  {
    "id": "kocury-49",
    "src": "/images/gallery/kocury/kocury_049.jpeg",
    "category": "kocury",
    "categoryLabel": "🦁 Kocury Hodowlane",
    "title": "Kocur Hodowlany #49",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocur Hodowlany)"
  },
  {
    "id": "kocury-50",
    "src": "/images/gallery/kocury/kocury_050.jpeg",
    "category": "kocury",
    "categoryLabel": "🦁 Kocury Hodowlane",
    "title": "Kocur Hodowlany #50",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocur Hodowlany)"
  },
  {
    "id": "kocury-51",
    "src": "/images/gallery/kocury/kocury_051.jpeg",
    "category": "kocury",
    "categoryLabel": "🦁 Kocury Hodowlane",
    "title": "Kocur Hodowlany #51",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocur Hodowlany)"
  },
  {
    "id": "matki-1",
    "src": "/images/gallery/matki/matki_001.jpeg",
    "category": "matki",
    "categoryLabel": "🌸 Matki Hodowlane",
    "title": "Kotka Hodowlana #1",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kotka Hodowlana)"
  },
  {
    "id": "matki-2",
    "src": "/images/gallery/matki/matki_002.jpg",
    "category": "matki",
    "categoryLabel": "🌸 Matki Hodowlane",
    "title": "Kotka Hodowlana #2",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kotka Hodowlana)"
  },
  {
    "id": "matki-3",
    "src": "/images/gallery/matki/matki_003.jpg",
    "category": "matki",
    "categoryLabel": "🌸 Matki Hodowlane",
    "title": "Kotka Hodowlana #3",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kotka Hodowlana)"
  },
  {
    "id": "matki-4",
    "src": "/images/gallery/matki/matki_004.jpg",
    "category": "matki",
    "categoryLabel": "🌸 Matki Hodowlane",
    "title": "Kotka Hodowlana #4",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kotka Hodowlana)"
  },
  {
    "id": "matki-5",
    "src": "/images/gallery/matki/matki_005.jpg",
    "category": "matki",
    "categoryLabel": "🌸 Matki Hodowlane",
    "title": "Kotka Hodowlana #5",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kotka Hodowlana)"
  },
  {
    "id": "matki-6",
    "src": "/images/gallery/matki/matki_006.jpg",
    "category": "matki",
    "categoryLabel": "🌸 Matki Hodowlane",
    "title": "Kotka Hodowlana #6",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kotka Hodowlana)"
  },
  {
    "id": "matki-7",
    "src": "/images/gallery/matki/matki_007.jpeg",
    "category": "matki",
    "categoryLabel": "🌸 Matki Hodowlane",
    "title": "Kotka Hodowlana #7",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kotka Hodowlana)"
  },
  {
    "id": "matki-8",
    "src": "/images/gallery/matki/matki_008.jpeg",
    "category": "matki",
    "categoryLabel": "🌸 Matki Hodowlane",
    "title": "Kotka Hodowlana #8",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kotka Hodowlana)"
  },
  {
    "id": "matki-9",
    "src": "/images/gallery/matki/matki_009.jpeg",
    "category": "matki",
    "categoryLabel": "🌸 Matki Hodowlane",
    "title": "Kotka Hodowlana #9",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kotka Hodowlana)"
  },
  {
    "id": "matki-10",
    "src": "/images/gallery/matki/matki_010.jpeg",
    "category": "matki",
    "categoryLabel": "🌸 Matki Hodowlane",
    "title": "Kotka Hodowlana #10",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kotka Hodowlana)"
  },
  {
    "id": "matki-11",
    "src": "/images/gallery/matki/matki_011.jpeg",
    "category": "matki",
    "categoryLabel": "🌸 Matki Hodowlane",
    "title": "Kotka Hodowlana #11",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kotka Hodowlana)"
  },
  {
    "id": "matki-12",
    "src": "/images/gallery/matki/matki_012.jpeg",
    "category": "matki",
    "categoryLabel": "🌸 Matki Hodowlane",
    "title": "Kotka Hodowlana #12",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kotka Hodowlana)"
  },
  {
    "id": "matki-13",
    "src": "/images/gallery/matki/matki_013.jpeg",
    "category": "matki",
    "categoryLabel": "🌸 Matki Hodowlane",
    "title": "Kotka Hodowlana #13",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kotka Hodowlana)"
  },
  {
    "id": "matki-14",
    "src": "/images/gallery/matki/matki_014.jpeg",
    "category": "matki",
    "categoryLabel": "🌸 Matki Hodowlane",
    "title": "Kotka Hodowlana #14",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kotka Hodowlana)"
  },
  {
    "id": "matki-15",
    "src": "/images/gallery/matki/matki_015.jpeg",
    "category": "matki",
    "categoryLabel": "🌸 Matki Hodowlane",
    "title": "Kotka Hodowlana #15",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kotka Hodowlana)"
  },
  {
    "id": "matki-16",
    "src": "/images/gallery/matki/matki_016.jpeg",
    "category": "matki",
    "categoryLabel": "🌸 Matki Hodowlane",
    "title": "Kotka Hodowlana #16",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kotka Hodowlana)"
  },
  {
    "id": "matki-17",
    "src": "/images/gallery/matki/matki_017.jpeg",
    "category": "matki",
    "categoryLabel": "🌸 Matki Hodowlane",
    "title": "Kotka Hodowlana #17",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kotka Hodowlana)"
  },
  {
    "id": "matki-18",
    "src": "/images/gallery/matki/matki_018.jpeg",
    "category": "matki",
    "categoryLabel": "🌸 Matki Hodowlane",
    "title": "Kotka Hodowlana #18",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kotka Hodowlana)"
  },
  {
    "id": "matki-19",
    "src": "/images/gallery/matki/matki_019.jpeg",
    "category": "matki",
    "categoryLabel": "🌸 Matki Hodowlane",
    "title": "Kotka Hodowlana #19",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kotka Hodowlana)"
  },
  {
    "id": "matki-20",
    "src": "/images/gallery/matki/matki_020.jpeg",
    "category": "matki",
    "categoryLabel": "🌸 Matki Hodowlane",
    "title": "Kotka Hodowlana #20",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kotka Hodowlana)"
  },
  {
    "id": "matki-21",
    "src": "/images/gallery/matki/matki_021.jpeg",
    "category": "matki",
    "categoryLabel": "🌸 Matki Hodowlane",
    "title": "Kotka Hodowlana #21",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kotka Hodowlana)"
  },
  {
    "id": "matki-22",
    "src": "/images/gallery/matki/matki_022.jpeg",
    "category": "matki",
    "categoryLabel": "🌸 Matki Hodowlane",
    "title": "Kotka Hodowlana #22",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kotka Hodowlana)"
  },
  {
    "id": "matki-23",
    "src": "/images/gallery/matki/matki_023.jpeg",
    "category": "matki",
    "categoryLabel": "🌸 Matki Hodowlane",
    "title": "Kotka Hodowlana #23",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kotka Hodowlana)"
  },
  {
    "id": "matki-24",
    "src": "/images/gallery/matki/matki_024.jpeg",
    "category": "matki",
    "categoryLabel": "🌸 Matki Hodowlane",
    "title": "Kotka Hodowlana #24",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kotka Hodowlana)"
  },
  {
    "id": "matki-25",
    "src": "/images/gallery/matki/matki_025.jpeg",
    "category": "matki",
    "categoryLabel": "🌸 Matki Hodowlane",
    "title": "Kotka Hodowlana #25",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kotka Hodowlana)"
  },
  {
    "id": "matki-26",
    "src": "/images/gallery/matki/matki_026.jpeg",
    "category": "matki",
    "categoryLabel": "🌸 Matki Hodowlane",
    "title": "Kotka Hodowlana #26",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kotka Hodowlana)"
  },
  {
    "id": "matki-27",
    "src": "/images/gallery/matki/matki_027.jpeg",
    "category": "matki",
    "categoryLabel": "🌸 Matki Hodowlane",
    "title": "Kotka Hodowlana #27",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kotka Hodowlana)"
  },
  {
    "id": "mlode-1",
    "src": "/images/gallery/mlode/mlode_001.jpeg",
    "category": "mlode",
    "categoryLabel": "🍼 Młode i Maluchy",
    "title": "Kocię Maine Coon #1",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocię Maine Coon)"
  },
  {
    "id": "mlode-2",
    "src": "/images/gallery/mlode/mlode_002.jpeg",
    "category": "mlode",
    "categoryLabel": "🍼 Młode i Maluchy",
    "title": "Kocię Maine Coon #2",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocię Maine Coon)"
  },
  {
    "id": "mlode-3",
    "src": "/images/gallery/mlode/mlode_003.jpeg",
    "category": "mlode",
    "categoryLabel": "🍼 Młode i Maluchy",
    "title": "Kocię Maine Coon #3",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocię Maine Coon)"
  },
  {
    "id": "mlode-4",
    "src": "/images/gallery/mlode/mlode_004.jpeg",
    "category": "mlode",
    "categoryLabel": "🍼 Młode i Maluchy",
    "title": "Kocię Maine Coon #4",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocię Maine Coon)"
  },
  {
    "id": "mlode-5",
    "src": "/images/gallery/mlode/mlode_005.jpeg",
    "category": "mlode",
    "categoryLabel": "🍼 Młode i Maluchy",
    "title": "Kocię Maine Coon #5",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocię Maine Coon)"
  },
  {
    "id": "mlode-6",
    "src": "/images/gallery/mlode/mlode_006.jpeg",
    "category": "mlode",
    "categoryLabel": "🍼 Młode i Maluchy",
    "title": "Kocię Maine Coon #6",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocię Maine Coon)"
  },
  {
    "id": "mlode-7",
    "src": "/images/gallery/mlode/mlode_007.jpeg",
    "category": "mlode",
    "categoryLabel": "🍼 Młode i Maluchy",
    "title": "Kocię Maine Coon #7",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocię Maine Coon)"
  },
  {
    "id": "mlode-8",
    "src": "/images/gallery/mlode/mlode_008.jpeg",
    "category": "mlode",
    "categoryLabel": "🍼 Młode i Maluchy",
    "title": "Kocię Maine Coon #8",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocię Maine Coon)"
  },
  {
    "id": "mlode-9",
    "src": "/images/gallery/mlode/mlode_009.jpeg",
    "category": "mlode",
    "categoryLabel": "🍼 Młode i Maluchy",
    "title": "Kocię Maine Coon #9",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocię Maine Coon)"
  },
  {
    "id": "mlode-10",
    "src": "/images/gallery/mlode/mlode_010.jpeg",
    "category": "mlode",
    "categoryLabel": "🍼 Młode i Maluchy",
    "title": "Kocię Maine Coon #10",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocię Maine Coon)"
  },
  {
    "id": "mlode-11",
    "src": "/images/gallery/mlode/mlode_011.jpeg",
    "category": "mlode",
    "categoryLabel": "🍼 Młode i Maluchy",
    "title": "Kocię Maine Coon #11",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocię Maine Coon)"
  },
  {
    "id": "mlode-12",
    "src": "/images/gallery/mlode/mlode_012.jpeg",
    "category": "mlode",
    "categoryLabel": "🍼 Młode i Maluchy",
    "title": "Kocię Maine Coon #12",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocię Maine Coon)"
  },
  {
    "id": "mlode-13",
    "src": "/images/gallery/mlode/mlode_013.jpeg",
    "category": "mlode",
    "categoryLabel": "🍼 Młode i Maluchy",
    "title": "Kocię Maine Coon #13",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocię Maine Coon)"
  },
  {
    "id": "mlode-14",
    "src": "/images/gallery/mlode/mlode_014.jpeg",
    "category": "mlode",
    "categoryLabel": "🍼 Młode i Maluchy",
    "title": "Kocię Maine Coon #14",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocię Maine Coon)"
  },
  {
    "id": "mlode-15",
    "src": "/images/gallery/mlode/mlode_015.jpeg",
    "category": "mlode",
    "categoryLabel": "🍼 Młode i Maluchy",
    "title": "Kocię Maine Coon #15",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocię Maine Coon)"
  },
  {
    "id": "mlode-16",
    "src": "/images/gallery/mlode/mlode_016.jpeg",
    "category": "mlode",
    "categoryLabel": "🍼 Młode i Maluchy",
    "title": "Kocię Maine Coon #16",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocię Maine Coon)"
  },
  {
    "id": "mlode-17",
    "src": "/images/gallery/mlode/mlode_017.jpeg",
    "category": "mlode",
    "categoryLabel": "🍼 Młode i Maluchy",
    "title": "Kocię Maine Coon #17",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocię Maine Coon)"
  },
  {
    "id": "mlode-18",
    "src": "/images/gallery/mlode/mlode_018.jpeg",
    "category": "mlode",
    "categoryLabel": "🍼 Młode i Maluchy",
    "title": "Kocię Maine Coon #18",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocię Maine Coon)"
  },
  {
    "id": "mlode-19",
    "src": "/images/gallery/mlode/mlode_019.jpeg",
    "category": "mlode",
    "categoryLabel": "🍼 Młode i Maluchy",
    "title": "Kocię Maine Coon #19",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocię Maine Coon)"
  },
  {
    "id": "mlode-20",
    "src": "/images/gallery/mlode/mlode_020.jpeg",
    "category": "mlode",
    "categoryLabel": "🍼 Młode i Maluchy",
    "title": "Kocię Maine Coon #20",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocię Maine Coon)"
  },
  {
    "id": "mlode-21",
    "src": "/images/gallery/mlode/mlode_021.jpeg",
    "category": "mlode",
    "categoryLabel": "🍼 Młode i Maluchy",
    "title": "Kocię Maine Coon #21",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocię Maine Coon)"
  },
  {
    "id": "mlode-22",
    "src": "/images/gallery/mlode/mlode_022.jpeg",
    "category": "mlode",
    "categoryLabel": "🍼 Młode i Maluchy",
    "title": "Kocię Maine Coon #22",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocię Maine Coon)"
  },
  {
    "id": "mlode-23",
    "src": "/images/gallery/mlode/mlode_023.jpeg",
    "category": "mlode",
    "categoryLabel": "🍼 Młode i Maluchy",
    "title": "Kocię Maine Coon #23",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocię Maine Coon)"
  },
  {
    "id": "mlode-24",
    "src": "/images/gallery/mlode/mlode_024.jpeg",
    "category": "mlode",
    "categoryLabel": "🍼 Młode i Maluchy",
    "title": "Kocię Maine Coon #24",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocię Maine Coon)"
  },
  {
    "id": "mlode-25",
    "src": "/images/gallery/mlode/mlode_025.jpeg",
    "category": "mlode",
    "categoryLabel": "🍼 Młode i Maluchy",
    "title": "Kocię Maine Coon #25",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocię Maine Coon)"
  },
  {
    "id": "mlode-26",
    "src": "/images/gallery/mlode/mlode_026.jpeg",
    "category": "mlode",
    "categoryLabel": "🍼 Młode i Maluchy",
    "title": "Kocię Maine Coon #26",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocię Maine Coon)"
  },
  {
    "id": "mlode-27",
    "src": "/images/gallery/mlode/mlode_027.jpeg",
    "category": "mlode",
    "categoryLabel": "🍼 Młode i Maluchy",
    "title": "Kocię Maine Coon #27",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocię Maine Coon)"
  },
  {
    "id": "mlode-28",
    "src": "/images/gallery/mlode/mlode_028.jpeg",
    "category": "mlode",
    "categoryLabel": "🍼 Młode i Maluchy",
    "title": "Kocię Maine Coon #28",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocię Maine Coon)"
  },
  {
    "id": "mlode-29",
    "src": "/images/gallery/mlode/mlode_029.jpeg",
    "category": "mlode",
    "categoryLabel": "🍼 Młode i Maluchy",
    "title": "Kocię Maine Coon #29",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocię Maine Coon)"
  },
  {
    "id": "mlode-30",
    "src": "/images/gallery/mlode/mlode_030.jpeg",
    "category": "mlode",
    "categoryLabel": "🍼 Młode i Maluchy",
    "title": "Kocię Maine Coon #30",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocię Maine Coon)"
  },
  {
    "id": "mlode-31",
    "src": "/images/gallery/mlode/mlode_031.jpeg",
    "category": "mlode",
    "categoryLabel": "🍼 Młode i Maluchy",
    "title": "Kocię Maine Coon #31",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocię Maine Coon)"
  },
  {
    "id": "mlode-32",
    "src": "/images/gallery/mlode/mlode_032.jpeg",
    "category": "mlode",
    "categoryLabel": "🍼 Młode i Maluchy",
    "title": "Kocię Maine Coon #32",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocię Maine Coon)"
  },
  {
    "id": "mlode-33",
    "src": "/images/gallery/mlode/mlode_033.jpeg",
    "category": "mlode",
    "categoryLabel": "🍼 Młode i Maluchy",
    "title": "Kocię Maine Coon #33",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocię Maine Coon)"
  },
  {
    "id": "mlode-34",
    "src": "/images/gallery/mlode/mlode_034.jpeg",
    "category": "mlode",
    "categoryLabel": "🍼 Młode i Maluchy",
    "title": "Kocię Maine Coon #34",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocię Maine Coon)"
  },
  {
    "id": "mlode-35",
    "src": "/images/gallery/mlode/mlode_035.jpeg",
    "category": "mlode",
    "categoryLabel": "🍼 Młode i Maluchy",
    "title": "Kocię Maine Coon #35",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocię Maine Coon)"
  },
  {
    "id": "mlode-36",
    "src": "/images/gallery/mlode/mlode_036.jpeg",
    "category": "mlode",
    "categoryLabel": "🍼 Młode i Maluchy",
    "title": "Kocię Maine Coon #36",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocię Maine Coon)"
  },
  {
    "id": "mlode-37",
    "src": "/images/gallery/mlode/mlode_037.jpeg",
    "category": "mlode",
    "categoryLabel": "🍼 Młode i Maluchy",
    "title": "Kocię Maine Coon #37",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocię Maine Coon)"
  },
  {
    "id": "mlode-38",
    "src": "/images/gallery/mlode/mlode_038.jpeg",
    "category": "mlode",
    "categoryLabel": "🍼 Młode i Maluchy",
    "title": "Kocię Maine Coon #38",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocię Maine Coon)"
  },
  {
    "id": "mlode-39",
    "src": "/images/gallery/mlode/mlode_039.jpeg",
    "category": "mlode",
    "categoryLabel": "🍼 Młode i Maluchy",
    "title": "Kocię Maine Coon #39",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocię Maine Coon)"
  },
  {
    "id": "mlode-40",
    "src": "/images/gallery/mlode/mlode_040.jpeg",
    "category": "mlode",
    "categoryLabel": "🍼 Młode i Maluchy",
    "title": "Kocię Maine Coon #40",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocię Maine Coon)"
  },
  {
    "id": "mlode-41",
    "src": "/images/gallery/mlode/mlode_041.jpeg",
    "category": "mlode",
    "categoryLabel": "🍼 Młode i Maluchy",
    "title": "Kocię Maine Coon #41",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocię Maine Coon)"
  },
  {
    "id": "mlode-42",
    "src": "/images/gallery/mlode/mlode_042.jpeg",
    "category": "mlode",
    "categoryLabel": "🍼 Młode i Maluchy",
    "title": "Kocię Maine Coon #42",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocię Maine Coon)"
  },
  {
    "id": "mlode-43",
    "src": "/images/gallery/mlode/mlode_043.jpeg",
    "category": "mlode",
    "categoryLabel": "🍼 Młode i Maluchy",
    "title": "Kocię Maine Coon #43",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocię Maine Coon)"
  },
  {
    "id": "mlode-44",
    "src": "/images/gallery/mlode/mlode_044.jpeg",
    "category": "mlode",
    "categoryLabel": "🍼 Młode i Maluchy",
    "title": "Kocię Maine Coon #44",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocię Maine Coon)"
  },
  {
    "id": "mlode-45",
    "src": "/images/gallery/mlode/mlode_045.jpeg",
    "category": "mlode",
    "categoryLabel": "🍼 Młode i Maluchy",
    "title": "Kocię Maine Coon #45",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocię Maine Coon)"
  },
  {
    "id": "mlode-46",
    "src": "/images/gallery/mlode/mlode_046.jpeg",
    "category": "mlode",
    "categoryLabel": "🍼 Młode i Maluchy",
    "title": "Kocię Maine Coon #46",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocię Maine Coon)"
  },
  {
    "id": "mlode-47",
    "src": "/images/gallery/mlode/mlode_047.jpeg",
    "category": "mlode",
    "categoryLabel": "🍼 Młode i Maluchy",
    "title": "Kocię Maine Coon #47",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocię Maine Coon)"
  },
  {
    "id": "mlode-48",
    "src": "/images/gallery/mlode/mlode_048.jpeg",
    "category": "mlode",
    "categoryLabel": "🍼 Młode i Maluchy",
    "title": "Kocię Maine Coon #48",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocię Maine Coon)"
  },
  {
    "id": "mlode-49",
    "src": "/images/gallery/mlode/mlode_049.jpeg",
    "category": "mlode",
    "categoryLabel": "🍼 Młode i Maluchy",
    "title": "Kocię Maine Coon #49",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocię Maine Coon)"
  },
  {
    "id": "mlode-50",
    "src": "/images/gallery/mlode/mlode_050.jpeg",
    "category": "mlode",
    "categoryLabel": "🍼 Młode i Maluchy",
    "title": "Kocię Maine Coon #50",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocię Maine Coon)"
  },
  {
    "id": "mlode-51",
    "src": "/images/gallery/mlode/mlode_051.jpeg",
    "category": "mlode",
    "categoryLabel": "🍼 Młode i Maluchy",
    "title": "Kocię Maine Coon #51",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocię Maine Coon)"
  },
  {
    "id": "mlode-52",
    "src": "/images/gallery/mlode/mlode_052.jpeg",
    "category": "mlode",
    "categoryLabel": "🍼 Młode i Maluchy",
    "title": "Kocię Maine Coon #52",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocię Maine Coon)"
  },
  {
    "id": "mlode-53",
    "src": "/images/gallery/mlode/mlode_053.jpeg",
    "category": "mlode",
    "categoryLabel": "🍼 Młode i Maluchy",
    "title": "Kocię Maine Coon #53",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocię Maine Coon)"
  },
  {
    "id": "mlode-54",
    "src": "/images/gallery/mlode/mlode_054.jpeg",
    "category": "mlode",
    "categoryLabel": "🍼 Młode i Maluchy",
    "title": "Kocię Maine Coon #54",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocię Maine Coon)"
  },
  {
    "id": "mlode-55",
    "src": "/images/gallery/mlode/mlode_055.jpeg",
    "category": "mlode",
    "categoryLabel": "🍼 Młode i Maluchy",
    "title": "Kocię Maine Coon #55",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocię Maine Coon)"
  },
  {
    "id": "mlode-56",
    "src": "/images/gallery/mlode/mlode_056.jpeg",
    "category": "mlode",
    "categoryLabel": "🍼 Młode i Maluchy",
    "title": "Kocię Maine Coon #56",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocię Maine Coon)"
  },
  {
    "id": "mlode-57",
    "src": "/images/gallery/mlode/mlode_057.jpeg",
    "category": "mlode",
    "categoryLabel": "🍼 Młode i Maluchy",
    "title": "Kocię Maine Coon #57",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocię Maine Coon)"
  },
  {
    "id": "mlode-58",
    "src": "/images/gallery/mlode/mlode_058.jpeg",
    "category": "mlode",
    "categoryLabel": "🍼 Młode i Maluchy",
    "title": "Kocię Maine Coon #58",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocię Maine Coon)"
  },
  {
    "id": "mlode-59",
    "src": "/images/gallery/mlode/mlode_059.jpeg",
    "category": "mlode",
    "categoryLabel": "🍼 Młode i Maluchy",
    "title": "Kocię Maine Coon #59",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocię Maine Coon)"
  },
  {
    "id": "mlode-60",
    "src": "/images/gallery/mlode/mlode_060.jpeg",
    "category": "mlode",
    "categoryLabel": "🍼 Młode i Maluchy",
    "title": "Kocię Maine Coon #60",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocię Maine Coon)"
  },
  {
    "id": "mlode-61",
    "src": "/images/gallery/mlode/mlode_061.jpeg",
    "category": "mlode",
    "categoryLabel": "🍼 Młode i Maluchy",
    "title": "Kocię Maine Coon #61",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocię Maine Coon)"
  },
  {
    "id": "mlode-62",
    "src": "/images/gallery/mlode/mlode_062.jpeg",
    "category": "mlode",
    "categoryLabel": "🍼 Młode i Maluchy",
    "title": "Kocię Maine Coon #62",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocię Maine Coon)"
  },
  {
    "id": "mlode-63",
    "src": "/images/gallery/mlode/mlode_063.jpeg",
    "category": "mlode",
    "categoryLabel": "🍼 Młode i Maluchy",
    "title": "Kocię Maine Coon #63",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocię Maine Coon)"
  },
  {
    "id": "mlode-64",
    "src": "/images/gallery/mlode/mlode_064.jpeg",
    "category": "mlode",
    "categoryLabel": "🍼 Młode i Maluchy",
    "title": "Kocię Maine Coon #64",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocię Maine Coon)"
  },
  {
    "id": "mlode-65",
    "src": "/images/gallery/mlode/mlode_065.jpeg",
    "category": "mlode",
    "categoryLabel": "🍼 Młode i Maluchy",
    "title": "Kocię Maine Coon #65",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocię Maine Coon)"
  },
  {
    "id": "mlode-66",
    "src": "/images/gallery/mlode/mlode_066.jpeg",
    "category": "mlode",
    "categoryLabel": "🍼 Młode i Maluchy",
    "title": "Kocię Maine Coon #66",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocię Maine Coon)"
  },
  {
    "id": "mlode-67",
    "src": "/images/gallery/mlode/mlode_067.jpeg",
    "category": "mlode",
    "categoryLabel": "🍼 Młode i Maluchy",
    "title": "Kocię Maine Coon #67",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocię Maine Coon)"
  },
  {
    "id": "mlode-68",
    "src": "/images/gallery/mlode/mlode_068.jpeg",
    "category": "mlode",
    "categoryLabel": "🍼 Młode i Maluchy",
    "title": "Kocię Maine Coon #68",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocię Maine Coon)"
  },
  {
    "id": "mlode-69",
    "src": "/images/gallery/mlode/mlode_069.jpeg",
    "category": "mlode",
    "categoryLabel": "🍼 Młode i Maluchy",
    "title": "Kocię Maine Coon #69",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocię Maine Coon)"
  },
  {
    "id": "mlode-70",
    "src": "/images/gallery/mlode/mlode_070.jpeg",
    "category": "mlode",
    "categoryLabel": "🍼 Młode i Maluchy",
    "title": "Kocię Maine Coon #70",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocię Maine Coon)"
  },
  {
    "id": "mlode-71",
    "src": "/images/gallery/mlode/mlode_071.jpeg",
    "category": "mlode",
    "categoryLabel": "🍼 Młode i Maluchy",
    "title": "Kocię Maine Coon #71",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocię Maine Coon)"
  },
  {
    "id": "mlode-72",
    "src": "/images/gallery/mlode/mlode_072.jpeg",
    "category": "mlode",
    "categoryLabel": "🍼 Młode i Maluchy",
    "title": "Kocię Maine Coon #72",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocię Maine Coon)"
  },
  {
    "id": "mlode-73",
    "src": "/images/gallery/mlode/mlode_073.jpeg",
    "category": "mlode",
    "categoryLabel": "🍼 Młode i Maluchy",
    "title": "Kocię Maine Coon #73",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocię Maine Coon)"
  },
  {
    "id": "mlode-74",
    "src": "/images/gallery/mlode/mlode_074.jpeg",
    "category": "mlode",
    "categoryLabel": "🍼 Młode i Maluchy",
    "title": "Kocię Maine Coon #74",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocię Maine Coon)"
  },
  {
    "id": "mlode-75",
    "src": "/images/gallery/mlode/mlode_075.jpeg",
    "category": "mlode",
    "categoryLabel": "🍼 Młode i Maluchy",
    "title": "Kocię Maine Coon #75",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocię Maine Coon)"
  },
  {
    "id": "mlode-76",
    "src": "/images/gallery/mlode/mlode_076.jpeg",
    "category": "mlode",
    "categoryLabel": "🍼 Młode i Maluchy",
    "title": "Kocię Maine Coon #76",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocię Maine Coon)"
  },
  {
    "id": "mlode-77",
    "src": "/images/gallery/mlode/mlode_077.jpeg",
    "category": "mlode",
    "categoryLabel": "🍼 Młode i Maluchy",
    "title": "Kocię Maine Coon #77",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocię Maine Coon)"
  },
  {
    "id": "mlode-78",
    "src": "/images/gallery/mlode/mlode_078.jpeg",
    "category": "mlode",
    "categoryLabel": "🍼 Młode i Maluchy",
    "title": "Kocię Maine Coon #78",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocię Maine Coon)"
  },
  {
    "id": "mlode-79",
    "src": "/images/gallery/mlode/mlode_079.jpeg",
    "category": "mlode",
    "categoryLabel": "🍼 Młode i Maluchy",
    "title": "Kocię Maine Coon #79",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocię Maine Coon)"
  },
  {
    "id": "mlode-80",
    "src": "/images/gallery/mlode/mlode_080.jpeg",
    "category": "mlode",
    "categoryLabel": "🍼 Młode i Maluchy",
    "title": "Kocię Maine Coon #80",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocię Maine Coon)"
  },
  {
    "id": "mlode-81",
    "src": "/images/gallery/mlode/mlode_081.jpeg",
    "category": "mlode",
    "categoryLabel": "🍼 Młode i Maluchy",
    "title": "Kocię Maine Coon #81",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocię Maine Coon)"
  },
  {
    "id": "mlode-82",
    "src": "/images/gallery/mlode/mlode_082.jpeg",
    "category": "mlode",
    "categoryLabel": "🍼 Młode i Maluchy",
    "title": "Kocię Maine Coon #82",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocię Maine Coon)"
  },
  {
    "id": "mlode-83",
    "src": "/images/gallery/mlode/mlode_083.jpeg",
    "category": "mlode",
    "categoryLabel": "🍼 Młode i Maluchy",
    "title": "Kocię Maine Coon #83",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocię Maine Coon)"
  },
  {
    "id": "mlode-84",
    "src": "/images/gallery/mlode/mlode_084.jpeg",
    "category": "mlode",
    "categoryLabel": "🍼 Młode i Maluchy",
    "title": "Kocię Maine Coon #84",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocię Maine Coon)"
  },
  {
    "id": "mlode-85",
    "src": "/images/gallery/mlode/mlode_085.jpeg",
    "category": "mlode",
    "categoryLabel": "🍼 Młode i Maluchy",
    "title": "Kocię Maine Coon #85",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocię Maine Coon)"
  },
  {
    "id": "mlode-86",
    "src": "/images/gallery/mlode/mlode_086.jpeg",
    "category": "mlode",
    "categoryLabel": "🍼 Młode i Maluchy",
    "title": "Kocię Maine Coon #86",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocię Maine Coon)"
  },
  {
    "id": "mlode-87",
    "src": "/images/gallery/mlode/mlode_087.jpeg",
    "category": "mlode",
    "categoryLabel": "🍼 Młode i Maluchy",
    "title": "Kocię Maine Coon #87",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocię Maine Coon)"
  },
  {
    "id": "mlode-88",
    "src": "/images/gallery/mlode/mlode_088.jpeg",
    "category": "mlode",
    "categoryLabel": "🍼 Młode i Maluchy",
    "title": "Kocię Maine Coon #88",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocię Maine Coon)"
  },
  {
    "id": "mlode-89",
    "src": "/images/gallery/mlode/mlode_089.jpeg",
    "category": "mlode",
    "categoryLabel": "🍼 Młode i Maluchy",
    "title": "Kocię Maine Coon #89",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocię Maine Coon)"
  },
  {
    "id": "mlode-90",
    "src": "/images/gallery/mlode/mlode_090.jpeg",
    "category": "mlode",
    "categoryLabel": "🍼 Młode i Maluchy",
    "title": "Kocię Maine Coon #90",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocię Maine Coon)"
  },
  {
    "id": "mlode-91",
    "src": "/images/gallery/mlode/mlode_091.jpeg",
    "category": "mlode",
    "categoryLabel": "🍼 Młode i Maluchy",
    "title": "Kocię Maine Coon #91",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocię Maine Coon)"
  },
  {
    "id": "mlode-92",
    "src": "/images/gallery/mlode/mlode_092.jpeg",
    "category": "mlode",
    "categoryLabel": "🍼 Młode i Maluchy",
    "title": "Kocię Maine Coon #92",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocię Maine Coon)"
  },
  {
    "id": "mlode-93",
    "src": "/images/gallery/mlode/mlode_093.jpeg",
    "category": "mlode",
    "categoryLabel": "🍼 Młode i Maluchy",
    "title": "Kocię Maine Coon #93",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Kocię Maine Coon)"
  },
  {
    "id": "w-domu-1",
    "src": "/images/gallery/w-domu/w-domu_001.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #1",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-2",
    "src": "/images/gallery/w-domu/w-domu_002.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #2",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-3",
    "src": "/images/gallery/w-domu/w-domu_003.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #3",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-4",
    "src": "/images/gallery/w-domu/w-domu_004.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #4",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-5",
    "src": "/images/gallery/w-domu/w-domu_005.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #5",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-6",
    "src": "/images/gallery/w-domu/w-domu_006.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #6",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-7",
    "src": "/images/gallery/w-domu/w-domu_007.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #7",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-8",
    "src": "/images/gallery/w-domu/w-domu_008.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #8",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-9",
    "src": "/images/gallery/w-domu/w-domu_009.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #9",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-10",
    "src": "/images/gallery/w-domu/w-domu_010.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #10",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-11",
    "src": "/images/gallery/w-domu/w-domu_011.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #11",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-12",
    "src": "/images/gallery/w-domu/w-domu_012.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #12",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-13",
    "src": "/images/gallery/w-domu/w-domu_013.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #13",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-14",
    "src": "/images/gallery/w-domu/w-domu_014.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #14",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-15",
    "src": "/images/gallery/w-domu/w-domu_015.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #15",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-16",
    "src": "/images/gallery/w-domu/w-domu_016.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #16",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-17",
    "src": "/images/gallery/w-domu/w-domu_017.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #17",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-18",
    "src": "/images/gallery/w-domu/w-domu_018.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #18",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-19",
    "src": "/images/gallery/w-domu/w-domu_019.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #19",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-20",
    "src": "/images/gallery/w-domu/w-domu_020.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #20",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-21",
    "src": "/images/gallery/w-domu/w-domu_021.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #21",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-22",
    "src": "/images/gallery/w-domu/w-domu_022.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #22",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-23",
    "src": "/images/gallery/w-domu/w-domu_023.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #23",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-24",
    "src": "/images/gallery/w-domu/w-domu_024.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #24",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-25",
    "src": "/images/gallery/w-domu/w-domu_025.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #25",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-26",
    "src": "/images/gallery/w-domu/w-domu_026.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #26",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-27",
    "src": "/images/gallery/w-domu/w-domu_027.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #27",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-28",
    "src": "/images/gallery/w-domu/w-domu_028.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #28",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-29",
    "src": "/images/gallery/w-domu/w-domu_029.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #29",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-30",
    "src": "/images/gallery/w-domu/w-domu_030.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #30",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-31",
    "src": "/images/gallery/w-domu/w-domu_031.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #31",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-32",
    "src": "/images/gallery/w-domu/w-domu_032.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #32",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-33",
    "src": "/images/gallery/w-domu/w-domu_033.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #33",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-34",
    "src": "/images/gallery/w-domu/w-domu_034.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #34",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-35",
    "src": "/images/gallery/w-domu/w-domu_035.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #35",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-36",
    "src": "/images/gallery/w-domu/w-domu_036.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #36",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-37",
    "src": "/images/gallery/w-domu/w-domu_037.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #37",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-38",
    "src": "/images/gallery/w-domu/w-domu_038.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #38",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-39",
    "src": "/images/gallery/w-domu/w-domu_039.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #39",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-40",
    "src": "/images/gallery/w-domu/w-domu_040.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #40",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-41",
    "src": "/images/gallery/w-domu/w-domu_041.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #41",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-42",
    "src": "/images/gallery/w-domu/w-domu_042.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #42",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-43",
    "src": "/images/gallery/w-domu/w-domu_043.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #43",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-44",
    "src": "/images/gallery/w-domu/w-domu_044.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #44",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-45",
    "src": "/images/gallery/w-domu/w-domu_045.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #45",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-46",
    "src": "/images/gallery/w-domu/w-domu_046.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #46",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-47",
    "src": "/images/gallery/w-domu/w-domu_047.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #47",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-48",
    "src": "/images/gallery/w-domu/w-domu_048.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #48",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-49",
    "src": "/images/gallery/w-domu/w-domu_049.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #49",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-50",
    "src": "/images/gallery/w-domu/w-domu_050.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #50",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-51",
    "src": "/images/gallery/w-domu/w-domu_051.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #51",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-52",
    "src": "/images/gallery/w-domu/w-domu_052.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #52",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-53",
    "src": "/images/gallery/w-domu/w-domu_053.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #53",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-54",
    "src": "/images/gallery/w-domu/w-domu_054.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #54",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-55",
    "src": "/images/gallery/w-domu/w-domu_055.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #55",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-56",
    "src": "/images/gallery/w-domu/w-domu_056.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #56",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-57",
    "src": "/images/gallery/w-domu/w-domu_057.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #57",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-58",
    "src": "/images/gallery/w-domu/w-domu_058.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #58",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-59",
    "src": "/images/gallery/w-domu/w-domu_059.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #59",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-60",
    "src": "/images/gallery/w-domu/w-domu_060.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #60",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-61",
    "src": "/images/gallery/w-domu/w-domu_061.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #61",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-62",
    "src": "/images/gallery/w-domu/w-domu_062.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #62",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-63",
    "src": "/images/gallery/w-domu/w-domu_063.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #63",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-64",
    "src": "/images/gallery/w-domu/w-domu_064.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #64",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-65",
    "src": "/images/gallery/w-domu/w-domu_065.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #65",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-66",
    "src": "/images/gallery/w-domu/w-domu_066.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #66",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-67",
    "src": "/images/gallery/w-domu/w-domu_067.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #67",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-68",
    "src": "/images/gallery/w-domu/w-domu_068.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #68",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-69",
    "src": "/images/gallery/w-domu/w-domu_069.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #69",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-70",
    "src": "/images/gallery/w-domu/w-domu_070.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #70",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-71",
    "src": "/images/gallery/w-domu/w-domu_071.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #71",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-72",
    "src": "/images/gallery/w-domu/w-domu_072.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #72",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-73",
    "src": "/images/gallery/w-domu/w-domu_073.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #73",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-74",
    "src": "/images/gallery/w-domu/w-domu_074.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #74",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-75",
    "src": "/images/gallery/w-domu/w-domu_075.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #75",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-76",
    "src": "/images/gallery/w-domu/w-domu_076.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #76",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-77",
    "src": "/images/gallery/w-domu/w-domu_077.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #77",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-78",
    "src": "/images/gallery/w-domu/w-domu_078.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #78",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-79",
    "src": "/images/gallery/w-domu/w-domu_079.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #79",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-80",
    "src": "/images/gallery/w-domu/w-domu_080.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #80",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-81",
    "src": "/images/gallery/w-domu/w-domu_081.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #81",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-82",
    "src": "/images/gallery/w-domu/w-domu_082.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #82",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-83",
    "src": "/images/gallery/w-domu/w-domu_083.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #83",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-84",
    "src": "/images/gallery/w-domu/w-domu_084.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #84",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-85",
    "src": "/images/gallery/w-domu/w-domu_085.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #85",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-86",
    "src": "/images/gallery/w-domu/w-domu_086.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #86",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-87",
    "src": "/images/gallery/w-domu/w-domu_087.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #87",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-88",
    "src": "/images/gallery/w-domu/w-domu_088.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #88",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-89",
    "src": "/images/gallery/w-domu/w-domu_089.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #89",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-90",
    "src": "/images/gallery/w-domu/w-domu_090.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #90",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-91",
    "src": "/images/gallery/w-domu/w-domu_091.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #91",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-92",
    "src": "/images/gallery/w-domu/w-domu_092.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #92",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-93",
    "src": "/images/gallery/w-domu/w-domu_093.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #93",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-94",
    "src": "/images/gallery/w-domu/w-domu_094.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #94",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-95",
    "src": "/images/gallery/w-domu/w-domu_095.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #95",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-96",
    "src": "/images/gallery/w-domu/w-domu_096.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #96",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-97",
    "src": "/images/gallery/w-domu/w-domu_097.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #97",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-98",
    "src": "/images/gallery/w-domu/w-domu_098.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #98",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-99",
    "src": "/images/gallery/w-domu/w-domu_099.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #99",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-100",
    "src": "/images/gallery/w-domu/w-domu_100.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #100",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-101",
    "src": "/images/gallery/w-domu/w-domu_101.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #101",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-102",
    "src": "/images/gallery/w-domu/w-domu_102.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #102",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-103",
    "src": "/images/gallery/w-domu/w-domu_103.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #103",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-104",
    "src": "/images/gallery/w-domu/w-domu_104.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #104",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-105",
    "src": "/images/gallery/w-domu/w-domu_105.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #105",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-106",
    "src": "/images/gallery/w-domu/w-domu_106.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #106",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-107",
    "src": "/images/gallery/w-domu/w-domu_107.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #107",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-108",
    "src": "/images/gallery/w-domu/w-domu_108.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #108",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-109",
    "src": "/images/gallery/w-domu/w-domu_109.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #109",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-110",
    "src": "/images/gallery/w-domu/w-domu_110.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #110",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-111",
    "src": "/images/gallery/w-domu/w-domu_111.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #111",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-112",
    "src": "/images/gallery/w-domu/w-domu_112.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #112",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-113",
    "src": "/images/gallery/w-domu/w-domu_113.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #113",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-114",
    "src": "/images/gallery/w-domu/w-domu_114.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #114",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-115",
    "src": "/images/gallery/w-domu/w-domu_115.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #115",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-116",
    "src": "/images/gallery/w-domu/w-domu_116.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #116",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-117",
    "src": "/images/gallery/w-domu/w-domu_117.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #117",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-118",
    "src": "/images/gallery/w-domu/w-domu_118.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #118",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-119",
    "src": "/images/gallery/w-domu/w-domu_119.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #119",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-120",
    "src": "/images/gallery/w-domu/w-domu_120.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #120",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-121",
    "src": "/images/gallery/w-domu/w-domu_121.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #121",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-122",
    "src": "/images/gallery/w-domu/w-domu_122.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #122",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-123",
    "src": "/images/gallery/w-domu/w-domu_123.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #123",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-124",
    "src": "/images/gallery/w-domu/w-domu_124.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #124",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-125",
    "src": "/images/gallery/w-domu/w-domu_125.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #125",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "w-domu-126",
    "src": "/images/gallery/w-domu/w-domu_126.jpeg",
    "category": "w-domu",
    "categoryLabel": "🏡 Życie w Domu",
    "title": "Życie w Domu #126",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Życie w Domu)"
  },
  {
    "id": "wyprawka-1",
    "src": "/images/gallery/wyprawka/wyprawka_001.jpeg",
    "category": "wyprawka",
    "categoryLabel": "🎁 Wyprawka",
    "title": "Luksusowa Wyprawka #1",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Luksusowa Wyprawka)"
  },
  {
    "id": "wyprawka-2",
    "src": "/images/gallery/wyprawka/wyprawka_002.jpeg",
    "category": "wyprawka",
    "categoryLabel": "🎁 Wyprawka",
    "title": "Luksusowa Wyprawka #2",
    "caption": "Autentyczne zdjęcie z życia hodowli Koci Przyjaciel *PL (Luksusowa Wyprawka)"
  }
];
