// Autogenerated real cats and gallery data from C:\Users\Michu\Desktop\aga
export interface CatPhoto {
  id: string;
  src: string;
  width: number;
  height: number;
  aspect: 'landscape' | 'portrait' | 'square';
  category?: string;
  title?: string;
  originalFile?: string;
}

export const REAL_LOGO = '/logo.webp';
export const REAL_FACEBOOK_URL = 'https://www.facebook.com/profile.php?id=100063684877717';
export const REAL_INSTAGRAM_URL = 'https://www.instagram.com/koci_przyjaciel_pl'; // Placeholder gotowy na docelowy link
export const REAL_PHONE = '698 837 525';
export const REAL_PHONE_RAW = '+48698837525';
export const REAL_LOCATION = 'Wrocław i okolice, Dolny Śląsk';

export const MATKI_PHOTOS: CatPhoto[] = [
  {
    "id": "matka-1",
    "src": "/images/matki/matka_01.webp",
    "width": 1200,
    "height": 1600,
    "aspect": "portrait",
    "originalFile": "-08 at 20.32.41.jpeg"
  },
  {
    "id": "matka-2",
    "src": "/images/matki/matka_02.webp",
    "width": 1400,
    "height": 1050,
    "aspect": "landscape",
    "originalFile": "623268085_1393878742533381_3081836477528235974_n.jpg"
  },
  {
    "id": "matka-3",
    "src": "/images/matki/matka_03.webp",
    "width": 1400,
    "height": 1874,
    "aspect": "portrait",
    "originalFile": "625164041_1396437738944148_8776568149697568292_n.jpg"
  },
  {
    "id": "matka-4",
    "src": "/images/matki/matka_04.webp",
    "width": 1080,
    "height": 1440,
    "aspect": "portrait",
    "originalFile": "625237219_1396437675610821_7545104965061094659_n.jpg"
  },
  {
    "id": "matka-5",
    "src": "/images/matki/matka_05.webp",
    "width": 1080,
    "height": 1080,
    "aspect": "portrait",
    "originalFile": "626803895_1396437725610816_7297301571543465292_n.jpg"
  },
  {
    "id": "matka-6",
    "src": "/images/matki/matka_06.webp",
    "width": 1400,
    "height": 1916,
    "aspect": "portrait",
    "originalFile": "793000808_1575789181009002_1789400252854076882_n.jpg"
  },
  {
    "id": "matka-7",
    "src": "/images/matki/matka_07.webp",
    "width": 1400,
    "height": 1867,
    "aspect": "portrait",
    "originalFile": "WhatsApp Image 2026-09-08 at 20.32.40.jpeg"
  }
];

export const GALLERY_PHOTOS: CatPhoto[] = [
  {
    "id": "cat-1",
    "src": "/images/cats/cat_01.webp",
    "width": 960,
    "height": 1419,
    "aspect": "portrait",
    "category": "zycie_w_domu",
    "title": "Maine Coon Koci Przyjaciel #1",
    "originalFile": "649500621_1432601955327726_208871247220136105_n.jpg"
  },
  {
    "id": "cat-2",
    "src": "/images/cats/cat_02.webp",
    "width": 936,
    "height": 2048,
    "aspect": "portrait",
    "category": "kotki",
    "title": "Maine Coon Koci Przyjaciel #2",
    "originalFile": "660689252_1448416450412943_5143909756840844051_n.jpg"
  },
  {
    "id": "cat-3",
    "src": "/images/cats/cat_03.webp",
    "width": 1400,
    "height": 1867,
    "aspect": "portrait",
    "category": "kocury",
    "title": "Maine Coon Koci Przyjaciel #3",
    "originalFile": "685089260_1467210485200206_6510983724358534318_n.jpg"
  },
  {
    "id": "cat-4",
    "src": "/images/cats/cat_04.webp",
    "width": 1265,
    "height": 2048,
    "aspect": "portrait",
    "category": "kociaki",
    "title": "Maine Coon Koci Przyjaciel #4",
    "originalFile": "690319330_1474618344459420_1777968680353564477_n.jpg"
  },
  {
    "id": "cat-5",
    "src": "/images/cats/cat_05.webp",
    "width": 900,
    "height": 2000,
    "aspect": "portrait",
    "category": "zycie_w_domu",
    "title": "Maine Coon Koci Przyjaciel #5",
    "originalFile": "714765429_1749245882730310_151820564721031938_n.jfif"
  },
  {
    "id": "cat-6",
    "src": "/images/cats/cat_06.webp",
    "width": 900,
    "height": 2000,
    "aspect": "portrait",
    "category": "kocury",
    "title": "Maine Coon Koci Przyjaciel #6",
    "originalFile": "719427568_2016989679697328_4499652836225709481_n.jfif"
  },
  {
    "id": "cat-7",
    "src": "/images/cats/cat_07.webp",
    "width": 1400,
    "height": 1867,
    "aspect": "portrait",
    "category": "zycie_w_domu",
    "title": "Maine Coon Koci Przyjaciel #7",
    "originalFile": "720873993_1505815184673069_1493065021927276779_n.jpg"
  },
  {
    "id": "cat-8",
    "src": "/images/cats/cat_08.webp",
    "width": 1082,
    "height": 2048,
    "aspect": "portrait",
    "category": "kociaki",
    "title": "Maine Coon Koci Przyjaciel #8",
    "originalFile": "723014325_27555283504160519_7969630077930721971_n.jfif"
  },
  {
    "id": "cat-9",
    "src": "/images/cats/cat_09.webp",
    "width": 1122,
    "height": 1402,
    "aspect": "portrait",
    "category": "kocury",
    "title": "Maine Coon Koci Przyjaciel #9",
    "originalFile": "724478291_1928902547811841_8031055588732586395_n.jfif"
  },
  {
    "id": "cat-10",
    "src": "/images/cats/cat_10.webp",
    "width": 1400,
    "height": 1867,
    "aspect": "portrait",
    "category": "kotki",
    "title": "Maine Coon Koci Przyjaciel #10",
    "originalFile": "741613631_2032060597429356_7478638894326214150_n.jfif"
  },
  {
    "id": "cat-11",
    "src": "/images/cats/cat_11.webp",
    "width": 1400,
    "height": 1867,
    "aspect": "portrait",
    "category": "zycie_w_domu",
    "title": "Maine Coon Koci Przyjaciel #11",
    "originalFile": "744184748_1529952655592655_5406760095867920810_n.jpg"
  },
  {
    "id": "cat-12",
    "src": "/images/cats/cat_12.webp",
    "width": 1400,
    "height": 2019,
    "aspect": "portrait",
    "category": "kociaki",
    "title": "Maine Coon Koci Przyjaciel #12",
    "originalFile": "745282786_1532258165362104_7679269006485921657_n.jpg"
  },
  {
    "id": "cat-13",
    "src": "/images/cats/cat_13.webp",
    "width": 1155,
    "height": 2048,
    "aspect": "portrait",
    "category": "zycie_w_domu",
    "title": "Maine Coon Koci Przyjaciel #13",
    "originalFile": "746842944_1371451868242248_1024092881375184952_n.jfif"
  },
  {
    "id": "cat-14",
    "src": "/images/cats/cat_14.webp",
    "width": 1400,
    "height": 1867,
    "aspect": "portrait",
    "category": "kotki",
    "title": "Maine Coon Koci Przyjaciel #14",
    "originalFile": "747450354_1532790155308905_58084607483412629_n.jpg"
  },
  {
    "id": "cat-15",
    "src": "/images/cats/cat_15.webp",
    "width": 1400,
    "height": 1400,
    "aspect": "square",
    "category": "kocury",
    "title": "Maine Coon Koci Przyjaciel #15",
    "originalFile": "748499667_2544211222665274_6218615925522146374_n.jfif"
  },
  {
    "id": "cat-16",
    "src": "/images/cats/cat_16.webp",
    "width": 1400,
    "height": 1867,
    "aspect": "portrait",
    "category": "kociaki",
    "title": "Maine Coon Koci Przyjaciel #16",
    "originalFile": "753881024_1540647987856455_1951074540958120944_n.jpg"
  },
  {
    "id": "cat-17",
    "src": "/images/cats/cat_17.webp",
    "width": 1218,
    "height": 2048,
    "aspect": "portrait",
    "category": "zycie_w_domu",
    "title": "Maine Coon Koci Przyjaciel #17",
    "originalFile": "755373924_1005889849009186_1303801791014137452_n.jfif"
  },
  {
    "id": "cat-18",
    "src": "/images/cats/cat_18.webp",
    "width": 945,
    "height": 1273,
    "aspect": "portrait",
    "category": "kocury",
    "title": "Maine Coon Koci Przyjaciel #18",
    "originalFile": "763824266_1373352564937763_2477423128490293300_n.jfif"
  },
  {
    "id": "cat-19",
    "src": "/images/cats/cat_19.webp",
    "width": 1152,
    "height": 2048,
    "aspect": "portrait",
    "category": "zycie_w_domu",
    "title": "Maine Coon Koci Przyjaciel #19",
    "originalFile": "766748056_1552536800000907_6447494146509324601_n.jpg"
  },
  {
    "id": "cat-20",
    "src": "/images/cats/cat_20.webp",
    "width": 1208,
    "height": 1599,
    "aspect": "portrait",
    "category": "kociaki",
    "title": "Maine Coon Koci Przyjaciel #20",
    "originalFile": "773756787_1680127929749018_1564117352974330138_n.jfif"
  },
  {
    "id": "cat-21",
    "src": "/images/cats/cat_21.webp",
    "width": 1400,
    "height": 1301,
    "aspect": "landscape",
    "category": "kocury",
    "title": "Maine Coon Koci Przyjaciel #21",
    "originalFile": "774595458_1527868458616948_6675842402311077191_n.jfif"
  },
  {
    "id": "cat-22",
    "src": "/images/cats/cat_22.webp",
    "width": 752,
    "height": 1500,
    "aspect": "portrait",
    "category": "kotki",
    "title": "Maine Coon Koci Przyjaciel #22",
    "originalFile": "774835839_1392038789784851_895114201758346589_n.jfif"
  },
  {
    "id": "cat-23",
    "src": "/images/cats/cat_23.webp",
    "width": 1400,
    "height": 1050,
    "aspect": "landscape",
    "category": "zycie_w_domu",
    "title": "Maine Coon Koci Przyjaciel #23",
    "originalFile": "774888187_28043726958628777_7446868748821696128_n.jfif"
  },
  {
    "id": "cat-24",
    "src": "/images/cats/cat_24.webp",
    "width": 828,
    "height": 2048,
    "aspect": "portrait",
    "category": "kociaki",
    "title": "Maine Coon Koci Przyjaciel #24",
    "originalFile": "776383533_2279970752774885_3304953370405976235_n.jfif"
  },
  {
    "id": "cat-25",
    "src": "/images/cats/cat_25.webp",
    "width": 1152,
    "height": 2048,
    "aspect": "portrait",
    "category": "zycie_w_domu",
    "title": "Maine Coon Koci Przyjaciel #25",
    "originalFile": "785282295_933350773154515_3761953253871782677_n.jfif"
  },
  {
    "id": "cat-26",
    "src": "/images/cats/cat_26.webp",
    "width": 1400,
    "height": 1867,
    "aspect": "portrait",
    "category": "kotki",
    "title": "Maine Coon Koci Przyjaciel #26",
    "originalFile": "786060360_1948363282527547_394566663146954278_n.jfif"
  },
  {
    "id": "cat-27",
    "src": "/images/cats/cat_27.webp",
    "width": 1400,
    "height": 788,
    "aspect": "landscape",
    "category": "kocury",
    "title": "Maine Coon Koci Przyjaciel #27",
    "originalFile": "787160643_1569844511603469_3113507995771196536_n.jpg"
  },
  {
    "id": "cat-28",
    "src": "/images/cats/cat_28.webp",
    "width": 1152,
    "height": 2048,
    "aspect": "portrait",
    "category": "kociaki",
    "title": "Maine Coon Koci Przyjaciel #28",
    "originalFile": "787873215_1572628791325041_1246133450279951671_n.jpg"
  },
  {
    "id": "cat-29",
    "src": "/images/cats/cat_29.webp",
    "width": 1152,
    "height": 2048,
    "aspect": "portrait",
    "category": "zycie_w_domu",
    "title": "Maine Coon Koci Przyjaciel #29",
    "originalFile": "789109571_1572811601306760_338903405116383927_n.jpg"
  },
  {
    "id": "cat-30",
    "src": "/images/cats/cat_30.webp",
    "width": 1152,
    "height": 2048,
    "aspect": "portrait",
    "category": "kocury",
    "title": "Maine Coon Koci Przyjaciel #30",
    "originalFile": "789213878_1572835734637680_3828838205216811485_n.jpg"
  },
  {
    "id": "cat-31",
    "src": "/images/cats/cat_31.webp",
    "width": 1152,
    "height": 2048,
    "aspect": "portrait",
    "category": "zycie_w_domu",
    "title": "Maine Coon Koci Przyjaciel #31",
    "originalFile": "789973205_1943285239679569_9080478182134713062_n.jfif"
  },
  {
    "id": "cat-32",
    "src": "/images/cats/cat_32.webp",
    "width": 1152,
    "height": 2048,
    "aspect": "portrait",
    "category": "kociaki",
    "title": "Maine Coon Koci Przyjaciel #32",
    "originalFile": "791014439_1575657041022216_7908707298259563240_n.jpg"
  },
  {
    "id": "cat-33",
    "src": "/images/cats/cat_33.webp",
    "width": 1152,
    "height": 2048,
    "aspect": "portrait",
    "category": "kocury",
    "title": "Maine Coon Koci Przyjaciel #33",
    "originalFile": "793000808_1575789181009002_1789400252854076882_n.jpg"
  },
  {
    "id": "cat-34",
    "src": "/images/cats/cat_34.webp",
    "width": 1400,
    "height": 1867,
    "aspect": "portrait",
    "category": "kotki",
    "title": "Maine Coon Koci Przyjaciel #34",
    "originalFile": "WhatsApp Imadsdge 2026-09-08 at 20.28.17.jpeg"
  },
  {
    "id": "cat-35",
    "src": "/images/cats/cat_35.webp",
    "width": 1400,
    "height": 1874,
    "aspect": "portrait",
    "category": "zycie_w_domu",
    "title": "Maine Coon Koci Przyjaciel #35",
    "originalFile": "WhatsApp Image 2026-09-08 at 20.28.10.jpeg"
  },
  {
    "id": "cat-36",
    "src": "/images/cats/cat_36.webp",
    "width": 600,
    "height": 800,
    "aspect": "portrait",
    "category": "kociaki",
    "title": "Maine Coon Koci Przyjaciel #36",
    "originalFile": "WhatsApp Image 2026-09-08 at 21.31.55 (1).jpeg"
  },
  {
    "id": "cat-37",
    "src": "/images/cats/cat_37.webp",
    "width": 800,
    "height": 600,
    "aspect": "landscape",
    "category": "zycie_w_domu",
    "title": "Maine Coon Koci Przyjaciel #37",
    "originalFile": "WhatsApp Image 2026-09-08 at 21.31.55 (2).jpeg"
  },
  {
    "id": "cat-38",
    "src": "/images/cats/cat_38.webp",
    "width": 600,
    "height": 800,
    "aspect": "portrait",
    "category": "kotki",
    "title": "Maine Coon Koci Przyjaciel #38",
    "originalFile": "WhatsApp Image 2026-09-08 at 21.31.55.jpeg"
  },
  {
    "id": "cat-39",
    "src": "/images/cats/cat_39.webp",
    "width": 600,
    "height": 800,
    "aspect": "portrait",
    "category": "kocury",
    "title": "Maine Coon Koci Przyjaciel #39",
    "originalFile": "WhatsApp Image 2026-09-08 at 21.31.56 (1).jpeg"
  },
  {
    "id": "cat-40",
    "src": "/images/cats/cat_40.webp",
    "width": 800,
    "height": 600,
    "aspect": "landscape",
    "category": "kociaki",
    "title": "Maine Coon Koci Przyjaciel #40",
    "originalFile": "WhatsApp Image 2026-09-08 at 21.31.56.jpeg"
  },
  {
    "id": "cat-41",
    "src": "/images/cats/cat_41.webp",
    "width": 600,
    "height": 800,
    "aspect": "portrait",
    "category": "zycie_w_domu",
    "title": "Maine Coon Koci Przyjaciel #41",
    "originalFile": "WhatsApp Image 2026-09-08 at 21.31.57.jpeg"
  },
  {
    "id": "cat-42",
    "src": "/images/cats/cat_42.webp",
    "width": 600,
    "height": 800,
    "aspect": "portrait",
    "category": "kocury",
    "title": "Maine Coon Koci Przyjaciel #42",
    "originalFile": "WhatsApp Image 2026-09-08 at 21.31.58 (1).jpeg"
  },
  {
    "id": "cat-43",
    "src": "/images/cats/cat_43.webp",
    "width": 600,
    "height": 800,
    "aspect": "portrait",
    "category": "zycie_w_domu",
    "title": "Maine Coon Koci Przyjaciel #43",
    "originalFile": "WhatsApp Image 2026-09-08 at 21.31.58 (2).jpeg"
  },
  {
    "id": "cat-44",
    "src": "/images/cats/cat_44.webp",
    "width": 600,
    "height": 800,
    "aspect": "portrait",
    "category": "kociaki",
    "title": "Maine Coon Koci Przyjaciel #44",
    "originalFile": "WhatsApp Image 2026-09-08 at 21.31.58 (3).jpeg"
  },
  {
    "id": "cat-45",
    "src": "/images/cats/cat_45.webp",
    "width": 600,
    "height": 800,
    "aspect": "portrait",
    "category": "kocury",
    "title": "Maine Coon Koci Przyjaciel #45",
    "originalFile": "WhatsApp Image 2026-09-08 at 21.31.58 (4).jpeg"
  },
  {
    "id": "cat-46",
    "src": "/images/cats/cat_46.webp",
    "width": 600,
    "height": 800,
    "aspect": "portrait",
    "category": "kotki",
    "title": "Maine Coon Koci Przyjaciel #46",
    "originalFile": "WhatsApp Image 2026-09-08 at 21.31.58.jpeg"
  },
  {
    "id": "cat-47",
    "src": "/images/cats/cat_47.webp",
    "width": 600,
    "height": 800,
    "aspect": "portrait",
    "category": "zycie_w_domu",
    "title": "Maine Coon Koci Przyjaciel #47",
    "originalFile": "WhatsApp Image 2026-09-08 at 21.31.59 (1).jpeg"
  },
  {
    "id": "cat-48",
    "src": "/images/cats/cat_48.webp",
    "width": 600,
    "height": 800,
    "aspect": "portrait",
    "category": "kociaki",
    "title": "Maine Coon Koci Przyjaciel #48",
    "originalFile": "WhatsApp Image 2026-09-08 at 21.31.59 (2).jpeg"
  },
  {
    "id": "cat-49",
    "src": "/images/cats/cat_49.webp",
    "width": 600,
    "height": 800,
    "aspect": "portrait",
    "category": "zycie_w_domu",
    "title": "Maine Coon Koci Przyjaciel #49",
    "originalFile": "WhatsApp Image 2026-09-08 at 21.31.59 (3).jpeg"
  },
  {
    "id": "cat-50",
    "src": "/images/cats/cat_50.webp",
    "width": 600,
    "height": 800,
    "aspect": "portrait",
    "category": "kotki",
    "title": "Maine Coon Koci Przyjaciel #50",
    "originalFile": "WhatsApp Image 2026-09-08 at 21.31.59.jpeg"
  },
  {
    "id": "cat-51",
    "src": "/images/cats/cat_51.webp",
    "width": 600,
    "height": 800,
    "aspect": "portrait",
    "category": "kocury",
    "title": "Maine Coon Koci Przyjaciel #51",
    "originalFile": "WhatsApp Image 2026-09-08 at 21.32.52 (1).jpeg"
  },
  {
    "id": "cat-52",
    "src": "/images/cats/cat_52.webp",
    "width": 600,
    "height": 800,
    "aspect": "portrait",
    "category": "kociaki",
    "title": "Maine Coon Koci Przyjaciel #52",
    "originalFile": "WhatsApp Image 2026-09-08 at 21.32.52.jpeg"
  },
  {
    "id": "cat-53",
    "src": "/images/cats/cat_53.webp",
    "width": 600,
    "height": 800,
    "aspect": "portrait",
    "category": "zycie_w_domu",
    "title": "Maine Coon Koci Przyjaciel #53",
    "originalFile": "WhatsApp Image 2026-09-08 at 21.32.53 (1).jpeg"
  },
  {
    "id": "cat-54",
    "src": "/images/cats/cat_54.webp",
    "width": 600,
    "height": 800,
    "aspect": "portrait",
    "category": "kocury",
    "title": "Maine Coon Koci Przyjaciel #54",
    "originalFile": "WhatsApp Image 2026-09-08 at 21.32.53 (2).jpeg"
  },
  {
    "id": "cat-55",
    "src": "/images/cats/cat_55.webp",
    "width": 600,
    "height": 800,
    "aspect": "portrait",
    "category": "zycie_w_domu",
    "title": "Maine Coon Koci Przyjaciel #55",
    "originalFile": "WhatsApp Image 2026-09-08 at 21.32.53 (3).jpeg"
  },
  {
    "id": "cat-56",
    "src": "/images/cats/cat_56.webp",
    "width": 600,
    "height": 800,
    "aspect": "portrait",
    "category": "kociaki",
    "title": "Maine Coon Koci Przyjaciel #56",
    "originalFile": "WhatsApp Image 2026-09-08 at 21.32.53 (4).jpeg"
  },
  {
    "id": "cat-57",
    "src": "/images/cats/cat_57.webp",
    "width": 600,
    "height": 800,
    "aspect": "portrait",
    "category": "kocury",
    "title": "Maine Coon Koci Przyjaciel #57",
    "originalFile": "WhatsApp Image 2026-09-08 at 21.32.53.jpeg"
  },
  {
    "id": "cat-58",
    "src": "/images/cats/cat_58.webp",
    "width": 600,
    "height": 800,
    "aspect": "portrait",
    "category": "kotki",
    "title": "Maine Coon Koci Przyjaciel #58",
    "originalFile": "WhatsApp Image 2026-09-08 at 21.34.14.jpeg"
  },
  {
    "id": "cat-59",
    "src": "/images/cats/cat_59.webp",
    "width": 736,
    "height": 653,
    "aspect": "landscape",
    "category": "zycie_w_domu",
    "title": "Maine Coon Koci Przyjaciel #59",
    "originalFile": "WhatsApp Image 2026-09-08 at 21.34.15 (1).jpeg"
  },
  {
    "id": "cat-60",
    "src": "/images/cats/cat_60.webp",
    "width": 616,
    "height": 782,
    "aspect": "portrait",
    "category": "kociaki",
    "title": "Maine Coon Koci Przyjaciel #60",
    "originalFile": "WhatsApp Image 2026-09-08 at 21.34.15 (2).jpeg"
  },
  {
    "id": "cat-61",
    "src": "/images/cats/cat_61.webp",
    "width": 600,
    "height": 800,
    "aspect": "portrait",
    "category": "zycie_w_domu",
    "title": "Maine Coon Koci Przyjaciel #61",
    "originalFile": "WhatsApp Image 2026-09-08 at 21.34.15 (3).jpeg"
  },
  {
    "id": "cat-62",
    "src": "/images/cats/cat_62.webp",
    "width": 800,
    "height": 600,
    "aspect": "landscape",
    "category": "kotki",
    "title": "Maine Coon Koci Przyjaciel #62",
    "originalFile": "WhatsApp Image 2026-09-08 at 21.34.15 (4).jpeg"
  },
  {
    "id": "cat-63",
    "src": "/images/cats/cat_63.webp",
    "width": 680,
    "height": 713,
    "aspect": "portrait",
    "category": "kocury",
    "title": "Maine Coon Koci Przyjaciel #63",
    "originalFile": "WhatsApp Image 2026-09-08 at 21.34.15.jpeg"
  },
  {
    "id": "cat-64",
    "src": "/images/cats/cat_64.webp",
    "width": 600,
    "height": 800,
    "aspect": "portrait",
    "category": "kociaki",
    "title": "Maine Coon Koci Przyjaciel #64",
    "originalFile": "WhatsApp Image 2026-09-08 at 21.34.16 (1).jpeg"
  },
  {
    "id": "cat-65",
    "src": "/images/cats/cat_65.webp",
    "width": 600,
    "height": 800,
    "aspect": "portrait",
    "category": "zycie_w_domu",
    "title": "Maine Coon Koci Przyjaciel #65",
    "originalFile": "WhatsApp Image 2026-09-08 at 21.34.16 (2).jpeg"
  },
  {
    "id": "cat-66",
    "src": "/images/cats/cat_66.webp",
    "width": 648,
    "height": 738,
    "aspect": "portrait",
    "category": "kocury",
    "title": "Maine Coon Koci Przyjaciel #66",
    "originalFile": "WhatsApp Image 2026-09-08 at 21.34.16 (3).jpeg"
  },
  {
    "id": "cat-67",
    "src": "/images/cats/cat_67.webp",
    "width": 600,
    "height": 800,
    "aspect": "portrait",
    "category": "zycie_w_domu",
    "title": "Maine Coon Koci Przyjaciel #67",
    "originalFile": "WhatsApp Image 2026-09-08 at 21.34.16 (4).jpeg"
  },
  {
    "id": "cat-68",
    "src": "/images/cats/cat_68.webp",
    "width": 600,
    "height": 800,
    "aspect": "portrait",
    "category": "kociaki",
    "title": "Maine Coon Koci Przyjaciel #68",
    "originalFile": "WhatsApp Image 2026-09-08 at 21.34.16 (5).jpeg"
  },
  {
    "id": "cat-69",
    "src": "/images/cats/cat_69.webp",
    "width": 600,
    "height": 800,
    "aspect": "portrait",
    "category": "kocury",
    "title": "Maine Coon Koci Przyjaciel #69",
    "originalFile": "WhatsApp Image 2026-09-08 at 21.34.16.jpeg"
  },
  {
    "id": "cat-70",
    "src": "/images/cats/cat_70.webp",
    "width": 600,
    "height": 800,
    "aspect": "portrait",
    "category": "kotki",
    "title": "Maine Coon Koci Przyjaciel #70",
    "originalFile": "WhatsApp Image 2026-09-08 at 21.34.17 (1).jpeg"
  },
  {
    "id": "cat-71",
    "src": "/images/cats/cat_71.webp",
    "width": 600,
    "height": 800,
    "aspect": "portrait",
    "category": "zycie_w_domu",
    "title": "Maine Coon Koci Przyjaciel #71",
    "originalFile": "WhatsApp Image 2026-09-08 at 21.34.17 (2).jpeg"
  },
  {
    "id": "cat-72",
    "src": "/images/cats/cat_72.webp",
    "width": 600,
    "height": 800,
    "aspect": "portrait",
    "category": "kociaki",
    "title": "Maine Coon Koci Przyjaciel #72",
    "originalFile": "WhatsApp Image 2026-09-08 at 21.34.17 (3).jpeg"
  },
  {
    "id": "cat-73",
    "src": "/images/cats/cat_73.webp",
    "width": 600,
    "height": 800,
    "aspect": "portrait",
    "category": "zycie_w_domu",
    "title": "Maine Coon Koci Przyjaciel #73",
    "originalFile": "WhatsApp Image 2026-09-08 at 21.34.17 (4).jpeg"
  },
  {
    "id": "cat-74",
    "src": "/images/cats/cat_74.webp",
    "width": 600,
    "height": 800,
    "aspect": "portrait",
    "category": "kotki",
    "title": "Maine Coon Koci Przyjaciel #74",
    "originalFile": "WhatsApp Image 2026-09-08 at 21.34.17.jpeg"
  },
  {
    "id": "cat-75",
    "src": "/images/cats/cat_75.webp",
    "width": 800,
    "height": 600,
    "aspect": "landscape",
    "category": "kocury",
    "title": "Maine Coon Koci Przyjaciel #75",
    "originalFile": "WhatsApp Image 2026-09-08 at 21.37.58 (1).jpeg"
  },
  {
    "id": "cat-76",
    "src": "/images/cats/cat_76.webp",
    "width": 800,
    "height": 600,
    "aspect": "landscape",
    "category": "kociaki",
    "title": "Maine Coon Koci Przyjaciel #76",
    "originalFile": "WhatsApp Image 2026-09-08 at 21.37.58 (2).jpeg"
  },
  {
    "id": "cat-77",
    "src": "/images/cats/cat_77.webp",
    "width": 600,
    "height": 800,
    "aspect": "portrait",
    "category": "zycie_w_domu",
    "title": "Maine Coon Koci Przyjaciel #77",
    "originalFile": "WhatsApp Image 2026-09-08 at 21.37.58 (3).jpeg"
  },
  {
    "id": "cat-78",
    "src": "/images/cats/cat_78.webp",
    "width": 576,
    "height": 832,
    "aspect": "portrait",
    "category": "kocury",
    "title": "Maine Coon Koci Przyjaciel #78",
    "originalFile": "WhatsApp Image 2026-09-08 at 21.37.58.jpeg"
  },
  {
    "id": "cat-79",
    "src": "/images/cats/cat_79.webp",
    "width": 600,
    "height": 800,
    "aspect": "portrait",
    "category": "zycie_w_domu",
    "title": "Maine Coon Koci Przyjaciel #79",
    "originalFile": "WhatsApp Image 2026-09-08 at 21.37.59 (1).jpeg"
  },
  {
    "id": "cat-80",
    "src": "/images/cats/cat_80.webp",
    "width": 600,
    "height": 800,
    "aspect": "portrait",
    "category": "kociaki",
    "title": "Maine Coon Koci Przyjaciel #80",
    "originalFile": "WhatsApp Image 2026-09-08 at 21.37.59 (2).jpeg"
  },
  {
    "id": "cat-81",
    "src": "/images/cats/cat_81.webp",
    "width": 600,
    "height": 800,
    "aspect": "portrait",
    "category": "kocury",
    "title": "Maine Coon Koci Przyjaciel #81",
    "originalFile": "WhatsApp Image 2026-09-08 at 21.37.59 (3).jpeg"
  },
  {
    "id": "cat-82",
    "src": "/images/cats/cat_82.webp",
    "width": 600,
    "height": 800,
    "aspect": "portrait",
    "category": "kotki",
    "title": "Maine Coon Koci Przyjaciel #82",
    "originalFile": "WhatsApp Image 2026-09-08 at 21.37.59 (4).jpeg"
  },
  {
    "id": "cat-83",
    "src": "/images/cats/cat_83.webp",
    "width": 600,
    "height": 800,
    "aspect": "portrait",
    "category": "zycie_w_domu",
    "title": "Maine Coon Koci Przyjaciel #83",
    "originalFile": "WhatsApp Image 2026-09-08 at 21.37.59.jpeg"
  },
  {
    "id": "cat-84",
    "src": "/images/cats/cat_84.webp",
    "width": 520,
    "height": 924,
    "aspect": "portrait",
    "category": "kociaki",
    "title": "Maine Coon Koci Przyjaciel #84",
    "originalFile": "WhatsApp Image 2026-09-08 at 21.38.00 (1).jpeg"
  },
  {
    "id": "cat-85",
    "src": "/images/cats/cat_85.webp",
    "width": 520,
    "height": 924,
    "aspect": "portrait",
    "category": "zycie_w_domu",
    "title": "Maine Coon Koci Przyjaciel #85",
    "originalFile": "WhatsApp Image 2026-09-08 at 21.38.00 (2).jpeg"
  },
  {
    "id": "cat-86",
    "src": "/images/cats/cat_86.webp",
    "width": 520,
    "height": 924,
    "aspect": "portrait",
    "category": "kotki",
    "title": "Maine Coon Koci Przyjaciel #86",
    "originalFile": "WhatsApp Image 2026-09-08 at 21.38.00 (3).jpeg"
  },
  {
    "id": "cat-87",
    "src": "/images/cats/cat_87.webp",
    "width": 408,
    "height": 1158,
    "aspect": "portrait",
    "category": "kocury",
    "title": "Maine Coon Koci Przyjaciel #87",
    "originalFile": "WhatsApp Image 2026-09-08 at 21.38.00 (4).jpeg"
  },
  {
    "id": "cat-88",
    "src": "/images/cats/cat_88.webp",
    "width": 600,
    "height": 800,
    "aspect": "portrait",
    "category": "kociaki",
    "title": "Maine Coon Koci Przyjaciel #88",
    "originalFile": "WhatsApp Image 2026-09-08 at 21.38.00 (5).jpeg"
  },
  {
    "id": "cat-89",
    "src": "/images/cats/cat_89.webp",
    "width": 600,
    "height": 800,
    "aspect": "portrait",
    "category": "zycie_w_domu",
    "title": "Maine Coon Koci Przyjaciel #89",
    "originalFile": "WhatsApp Image 2026-09-08 at 21.38.00.jpeg"
  },
  {
    "id": "cat-90",
    "src": "/images/cats/cat_90.webp",
    "width": 600,
    "height": 800,
    "aspect": "portrait",
    "category": "kocury",
    "title": "Maine Coon Koci Przyjaciel #90",
    "originalFile": "WhatsApp Image 2026-09-08 at 21.38.01 (1).jpeg"
  },
  {
    "id": "cat-91",
    "src": "/images/cats/cat_91.webp",
    "width": 600,
    "height": 800,
    "aspect": "portrait",
    "category": "zycie_w_domu",
    "title": "Maine Coon Koci Przyjaciel #91",
    "originalFile": "WhatsApp Image 2026-09-08 at 21.38.01 (2).jpeg"
  },
  {
    "id": "cat-92",
    "src": "/images/cats/cat_92.webp",
    "width": 600,
    "height": 800,
    "aspect": "portrait",
    "category": "kociaki",
    "title": "Maine Coon Koci Przyjaciel #92",
    "originalFile": "WhatsApp Image 2026-09-08 at 21.38.01.jpeg"
  },
  {
    "id": "cat-93",
    "src": "/images/cats/cat_93.webp",
    "width": 600,
    "height": 800,
    "aspect": "portrait",
    "category": "kocury",
    "title": "Maine Coon Koci Przyjaciel #93",
    "originalFile": "WhatsApp Image 2026-09-08 at 21.39.14 (1).jpeg"
  },
  {
    "id": "cat-94",
    "src": "/images/cats/cat_94.webp",
    "width": 600,
    "height": 800,
    "aspect": "portrait",
    "category": "kotki",
    "title": "Maine Coon Koci Przyjaciel #94",
    "originalFile": "WhatsApp Image 2026-09-08 at 21.39.14.jpeg"
  },
  {
    "id": "cat-95",
    "src": "/images/cats/cat_95.webp",
    "width": 600,
    "height": 800,
    "aspect": "portrait",
    "category": "zycie_w_domu",
    "title": "Maine Coon Koci Przyjaciel #95",
    "originalFile": "WhatsApp Image 2026-09-08 at 21.39.15 (1).jpeg"
  },
  {
    "id": "cat-96",
    "src": "/images/cats/cat_96.webp",
    "width": 712,
    "height": 667,
    "aspect": "landscape",
    "category": "kociaki",
    "title": "Maine Coon Koci Przyjaciel #96",
    "originalFile": "WhatsApp Image 2026-09-08 at 21.39.15 (2).jpeg"
  },
  {
    "id": "cat-97",
    "src": "/images/cats/cat_97.webp",
    "width": 600,
    "height": 800,
    "aspect": "portrait",
    "category": "zycie_w_domu",
    "title": "Maine Coon Koci Przyjaciel #97",
    "originalFile": "WhatsApp Image 2026-09-08 at 21.39.15.jpeg"
  },
  {
    "id": "cat-98",
    "src": "/images/cats/cat_98.webp",
    "width": 1200,
    "height": 1600,
    "aspect": "portrait",
    "category": "kotki",
    "title": "Maine Coon Koci Przyjaciel #98",
    "originalFile": "WhatsApp Imdage 2026-09-08 at 20.28.10.jpeg"
  }
];

// Best featured photos for specific sections — ręcznie wyselekcjonowane najlepsze ujęcia
export const HERO_CATS: CatPhoto[] = [
  {
    id: "cat-18",
    src: "/images/cats/cat_18.webp",
    width: 945,
    height: 1273,
    aspect: "portrait",
    category: "kocury",
    title: "Oficjalny portret z logo hodowli Koci Przyjaciel *PL",
    originalFile: "763824266_1373352564937763_2477423128490293300_n.jfif"
  },
  {
    id: "cat-24",
    src: "/images/cats/cat_24.webp",
    width: 828,
    height: 2048,
    aspect: "portrait",
    category: "kocury",
    title: "Czułość i bliskość — zachód słońca nad jeziorem",
    originalFile: "776383533_2279970752774885_3304953370405976235_n.jfif"
  },
  {
    id: "cat-9",
    src: "/images/cats/cat_09.webp",
    width: 1122,
    height: 1402,
    aspect: "portrait",
    category: "kociaki",
    title: "Mama i kociak — spokój w domowym zaciszu",
    originalFile: "724478291_1928902547811841_8031055588732586395_n.jfif"
  },
  {
    id: "matka-3",
    src: "/images/matki/matka_03.webp",
    width: 1400,
    height: 1874,
    aspect: "portrait",
    category: "matki",
    title: "Biały majestat — kotka o potężnej lwiej kryzie",
    originalFile: "625164041_1396437738944148_8776568149697568292_n.jpg"
  },
  {
    id: "cat-34",
    src: "/images/cats/cat_34.webp",
    width: 1200,
    height: 1600,
    aspect: "portrait",
    category: "kocury",
    title: "Srebrzysty kocur z imponującymi pędzlami na uszach",
    originalFile: "WhatsApp Image 2026-09-08 at 21.31.55 (1).jpeg"
  },
  {
    id: "matka-7",
    src: "/images/matki/matka_07.webp",
    width: 1400,
    height: 1867,
    aspect: "portrait",
    category: "kocury",
    title: "Prawdziwy gigant — ponad metr długości ciała",
    originalFile: "WhatsApp Image 2026-09-08 at 20.32.40.jpeg"
  }
];

export const KITTEN_FEATURED: CatPhoto[] = [
  {
    id: "cat-7",
    src: "/images/cats/cat_07.webp",
    width: 1400,
    height: 1867,
    aspect: "portrait",
    category: "kociaki",
    title: "Luna *PL — klasycznie pręgowana kotka",
    originalFile: "720873993_1505815184673069_1493065021927276779_n.jpg"
  },
  {
    id: "cat-8",
    src: "/images/cats/cat_08.webp",
    width: 1082,
    height: 2048,
    aspect: "portrait",
    category: "kociaki",
    title: "Leo *PL — srebrzysty klasyczny pręgowany",
    originalFile: "723014325_27555283504160519_7969630077930721971_n.jfif"
  },
  {
    id: "cat-10",
    src: "/images/cats/cat_10.webp",
    width: 1400,
    height: 1867,
    aspect: "portrait",
    category: "kociaki",
    title: "Yuki *PL — śnieżnobiały kociak o bursztynowych oczach",
    originalFile: "741613631_2032060597429356_7478638894326214150_n.jfif"
  },
  {
    id: "cat-30",
    src: "/images/cats/cat_30.webp",
    width: 1080,
    height: 1920,
    aspect: "portrait",
    category: "kociaki",
    title: "Kacper *PL — biały maluch o potężnych łapkach",
    originalFile: "WhatsApp Image 2026-09-08 at 21.31.58 (2).jpeg"
  },
  {
    id: "cat-17",
    src: "/images/cats/cat_17.webp",
    width: 1218,
    height: 2048,
    aspect: "portrait",
    category: "kociaki",
    title: "Arthur *PL — czarny dymny z wybitnym profilem",
    originalFile: "755373924_1005889849009186_1303801791014137452_n.jfif"
  },
  {
    id: "cat-20",
    src: "/images/cats/cat_20.webp",
    width: 1208,
    height: 1599,
    aspect: "portrait",
    category: "kociaki",
    title: "Maja *PL — szylkretowa kotka podczas zabawy na kanapie",
    originalFile: "773756787_1680127929749018_1564117352974330138_n.jfif"
  }
];

export const HOME_LIFE_FEATURED: CatPhoto[] = [
  {
    id: "cat-27",
    src: "/images/cats/cat_27.webp",
    width: 1920,
    height: 1080,
    aspect: "landscape",
    category: "zycie_w_domu",
    title: "100% socjalizacja z dziećmi — rodzina w ogrodzie",
    originalFile: "WhatsApp Image 2026-09-08 at 21.31.57.jpeg"
  },
  {
    id: "cat-26",
    src: "/images/cats/cat_26.webp",
    width: 1440,
    height: 1920,
    aspect: "portrait",
    category: "zycie_w_domu",
    title: "Zaufanie i spokój — kociak w ramionach nowego opiekuna",
    originalFile: "WhatsApp Image 2026-09-08 at 21.31.56 (1).jpeg"
  },
  {
    id: "cat-11",
    src: "/images/cats/cat_11.webp",
    width: 1400,
    height: 1867,
    aspect: "portrait",
    category: "zycie_w_domu",
    title: "Czysta miłość — czułość od pierwszych dni",
    originalFile: "744184748_1529952655592655_5406760095867920810_n.jpg"
  },
  {
    id: "cat-15",
    src: "/images/cats/cat_15.webp",
    width: 1400,
    height: 1400,
    aspect: "square",
    category: "zycie_w_domu",
    title: "Maine Coon na desce SUP — miłość do wody w praktyce",
    originalFile: "748499667_2544211222665274_6218615925522146374_n.jfif"
  },
  {
    id: "cat-28",
    src: "/images/cats/cat_28.webp",
    width: 1080,
    height: 1920,
    aspect: "portrait",
    category: "zycie_w_domu",
    title: "Królewska wyprawka dla każdego opuszczającego hodowlę kociaka",
    originalFile: "WhatsApp Image 2026-09-08 at 21.31.58.jpeg"
  },
  {
    id: "cat-32",
    src: "/images/cats/cat_32.webp",
    width: 1080,
    height: 1920,
    aspect: "portrait",
    category: "zycie_w_domu",
    title: "Certyfikowany rodowód Felis Polonia (FPL / FIFe)",
    originalFile: "WhatsApp Image 2026-09-08 at 21.31.59 (1).jpeg"
  },
  {
    id: "matka-2",
    src: "/images/matki/matka_02.webp",
    width: 1400,
    height: 1050,
    aspect: "landscape",
    category: "zycie_w_domu",
    title: "Harmonia w domu — kociak i królik na wspólnym dywanie",
    originalFile: "623268085_1393878742533381_3081836477528235974_n.jpg"
  },
  {
    id: "matka-5",
    src: "/images/matki/matka_05.webp",
    width: 1080,
    height: 1080,
    aspect: "square",
    category: "zycie_w_domu",
    title: "Relaks w salonie — 40 cm pióropusz ogona",
    originalFile: "626803895_1396437725610816_7297301571543465292_n.jpg"
  },
  {
    id: "cat-6",
    src: "/images/cats/cat_06.webp",
    width: 900,
    height: 2000,
    aspect: "portrait",
    category: "zycie_w_domu",
    title: "Słoneczny wybieg ogrodowy i pies w tle",
    originalFile: "719427568_2016989679697328_4499652836225709481_n.jfif"
  },
  {
    id: "cat-19",
    src: "/images/cats/cat_19.webp",
    width: 1152,
    height: 2048,
    aspect: "portrait",
    category: "zycie_w_domu",
    title: "Łagodny olbrzym odpoczywający na kolanach w ogrodzie",
    originalFile: "766748056_1552536800000907_6447494146509324601_n.jpg"
  }
];

